import fs from 'fs';

const SW_COURSES_REGISTRY = `
  // === Software Engineering ===
  'sw-fundamentals': {
    id: 'sw-fundamentals',
    emoji: '💻',
    title: 'คอมพิวเตอร์พื้นฐาน',
    fullTitle: 'คอมพิวเตอร์พื้นฐาน — Binary, CPU, OS, Network, Algorithm',
    subtitle: 'Binary → OS → Network → Data Structures → Algorithm',
    desc: 'เรียนรู้วิธีคอมพิวเตอร์ทำงาน Binary, CPU, RAM, OS, Network, Data Structures และ Algorithm พื้นฐานครบที่ทุก Dev ต้องรู้',
    level: 'เริ่มต้น',
    levelColor: '#6366f1',
    chapterCount: 8,
    duration: '~3 ชม.',
    tags: ['Binary', 'CPU', 'OS', 'Network', 'Algorithm', 'Data Structures'],
    dataFile: 'sw-fundamentals',
    cover: '/images/sw-fundamentals/cover.png',
    isFree: true,
  },
  'sw-git': {
    id: 'sw-git',
    emoji: '🖥️',
    title: 'Terminal & Git',
    fullTitle: 'Terminal & Git — Command Line, Git, GitHub, Branch, PR',
    subtitle: 'Terminal → Git Workflow → GitHub → Team Collaboration → Shell Script',
    desc: 'เรียน Terminal, Git และ GitHub ตั้งแต่ต้น Branch, Merge, PR, Team workflow จนถึง Shell Script สิ่งที่ทุก Dev ใช้ทุกวัน',
    level: 'เริ่มต้น',
    levelColor: '#10b981',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['Terminal', 'Git', 'GitHub', 'Branch', 'PR', 'Shell Script'],
    dataFile: 'sw-git',
    cover: '/images/sw-git/cover.png',
    isFree: true,
  },
  'sw-thinking': {
    id: 'sw-thinking',
    emoji: '🧠',
    title: 'คิดแบบ Programmer',
    fullTitle: 'คิดแบบ Programmer — Algorithm, Logic, Problem Solving, Big O',
    subtitle: 'Decomposition → Patterns → Abstraction → Algorithm → Big O',
    desc: 'ฝึกคิดแบบ Programmer ด้วย Computational Thinking, Algorithm Design, Big O Notation, Recursion และ Problem Solving Framework',
    level: 'เริ่มต้น',
    levelColor: '#8b5cf6',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['Algorithm', 'Big O', 'Recursion', 'Problem Solving', 'Logic'],
    dataFile: 'sw-thinking',
    cover: '/images/sw-thinking/cover.png',
    isFree: true,
  },
  'sw-html-css': {
    id: 'sw-html-css',
    emoji: '🌈',
    title: 'HTML & CSS Zero to Hero',
    fullTitle: 'HTML & CSS Zero to Hero — Flexbox, Grid, Responsive, Animation',
    subtitle: 'HTML → CSS → Flexbox → Grid → Responsive → Animations → Deploy',
    desc: 'เรียน HTML และ CSS ตั้งแต่ศูนย์ Flexbox, Grid, Responsive Design, Animations จนถึง Build เว็บไซต์ Portfolio จริง',
    level: 'เริ่มต้น',
    levelColor: '#f97316',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['HTML', 'CSS', 'Flexbox', 'Grid', 'Responsive', 'Animation'],
    dataFile: 'sw-html-css',
    cover: '/images/sw-html-css/cover.png',
    isFree: true,
  },
  'sw-javascript': {
    id: 'sw-javascript',
    emoji: '📚',
    title: 'JavaScript พื้นฐาน',
    fullTitle: 'JavaScript พื้นฐาน — DOM, Events, Async/Await, Fetch API',
    subtitle: 'Variables → Functions → DOM → Events → Async → Fetch → Project',
    desc: 'เรียน JavaScript ตั้งแต่ต้น Variables, Functions, DOM, Events, Async/Await, Fetch API จนถึง Build Todo App จริง',
    level: 'เริ่มต้น',
    levelColor: '#f59e0b',
    chapterCount: 16,
    duration: '~6 ชม.',
    tags: ['JavaScript', 'DOM', 'Events', 'Async/Await', 'Fetch API'],
    dataFile: 'sw-javascript',
    cover: '/images/sw-javascript/cover.png',
    isFree: true,
  },
  'sw-javascript-advanced': {
    id: 'sw-javascript-advanced',
    emoji: '⚡',
    title: 'JavaScript Advanced',
    fullTitle: 'JavaScript Advanced — Closures, Prototype, FP, Workers, Security',
    subtitle: 'Closures → Prototype → Functional → Generators → Performance',
    desc: 'เรียน JavaScript ผู้เชี่ยวชาญ Closures ลึก, Prototype Chain, Functional Programming, Generators, Web Workers, Memory Management',
    level: 'กลาง-สูง',
    levelColor: '#ef4444',
    chapterCount: 12,
    duration: '~4 ชม.',
    tags: ['JavaScript', 'Closures', 'Functional', 'Generators', 'Performance', 'Security'],
    dataFile: 'sw-javascript-advanced',
    cover: '/images/sw-javascript-advanced/cover.png',
    isFree: true,
  },
  'sw-react': {
    id: 'sw-react',
    emoji: '⚛️',
    title: 'React จากศูนย์',
    fullTitle: 'React จากศูนย์ — Components, Hooks, Context, Router',
    subtitle: 'Components → Hooks → State → Context → Router → Testing → Project',
    desc: 'เรียน React ตั้งแต่ต้น Components, useState, useEffect, Context API, Custom Hooks, React Router จนถึง Build Task Management App จริง',
    level: 'เริ่มต้น-กลาง',
    levelColor: '#61dafb',
    chapterCount: 16,
    duration: '~6 ชม.',
    tags: ['React', 'Hooks', 'useState', 'Context', 'React Router', 'Testing'],
    dataFile: 'sw-react',
    cover: '/images/sw-react/cover.png',
    isFree: true,
  },
  'sw-nextjs': {
    id: 'sw-nextjs',
    emoji: '▲',
    title: 'Next.js Fullstack',
    fullTitle: 'Next.js Fullstack — App Router, Auth, Database, Deploy Vercel',
    subtitle: 'App Router → Server Components → Auth → Prisma → Deploy',
    desc: 'เรียน Next.js 14+ App Router, Server Components, API Routes, Server Actions, NextAuth, Prisma ORM จนถึง Deploy Blog Platform จริง',
    level: 'กลาง',
    levelColor: '#ffffff',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['Next.js', 'App Router', 'Server Components', 'NextAuth', 'Prisma', 'Vercel'],
    dataFile: 'sw-nextjs',
    cover: '/images/sw-nextjs/cover.png',
    isFree: true,
  },
  'sw-typescript': {
    id: 'sw-typescript',
    emoji: '📘',
    title: 'TypeScript สำหรับ Dev',
    fullTitle: 'TypeScript สำหรับ Dev — Types, Generics, Utility Types, React',
    subtitle: 'Types → Interfaces → Generics → Utility Types → React+TS',
    desc: 'เรียน TypeScript ตั้งแต่ต้น Types, Interfaces, Generics, Advanced Types, Utility Types และ TypeScript ใน React',
    level: 'กลาง',
    levelColor: '#3178c6',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['TypeScript', 'Generics', 'Types', 'Utility Types', 'React'],
    dataFile: 'sw-typescript',
    cover: '/images/sw-typescript/cover.png',
    isFree: true,
  },
  'sw-python-backend': {
    id: 'sw-python-backend',
    emoji: '🐍',
    title: 'Python Backend',
    fullTitle: 'Python Backend — OOP, Async, SQLAlchemy, Testing, Celery',
    subtitle: 'OOP → Async → SQLAlchemy → Testing → Celery → Production',
    desc: 'เรียน Python สำหรับ Backend OOP, Async, SQLAlchemy, pytest, Celery, Environment Config และ Best Practices',
    level: 'เริ่มต้น-กลาง',
    levelColor: '#3776ab',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['Python', 'OOP', 'Async', 'SQLAlchemy', 'pytest', 'Celery'],
    dataFile: 'sw-python-backend',
    cover: '/images/sw-python-backend/cover.png',
    isFree: true,
  },
  'sw-fastapi': {
    id: 'sw-fastapi',
    emoji: '⚡',
    title: 'FastAPI สร้าง API จริง',
    fullTitle: 'FastAPI — REST API, JWT Auth, Database, WebSocket, Deploy',
    subtitle: 'Setup → Pydantic → Auth → Database → WebSocket → Docker',
    desc: 'สร้าง REST API ด้วย FastAPI ครบ Pydantic Validation, JWT Auth, SQLAlchemy, File Upload, WebSocket, Testing และ Docker Deploy',
    level: 'กลาง',
    levelColor: '#009688',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['FastAPI', 'Python', 'REST API', 'JWT', 'SQLAlchemy', 'Docker'],
    dataFile: 'sw-fastapi',
    cover: '/images/sw-fastapi/cover.png',
    isFree: true,
  },
  'sw-nodejs': {
    id: 'sw-nodejs',
    emoji: '🟩',
    title: 'Node.js + Express',
    fullTitle: 'Node.js + Express — REST API, Auth, Prisma, Socket.io, Deploy',
    subtitle: 'Express → Routing → Auth → Prisma → Socket.io → Testing',
    desc: 'สร้าง Backend ด้วย Node.js + Express, Prisma ORM, JWT Auth, Multer, Socket.io, Jest+Supertest จนถึง Build E-commerce API จริง',
    level: 'เริ่มต้น-กลาง',
    levelColor: '#8cc84b',
    chapterCount: 12,
    duration: '~4 ชม.',
    tags: ['Node.js', 'Express', 'Prisma', 'JWT', 'Socket.io', 'REST API'],
    dataFile: 'sw-nodejs',
    cover: '/images/sw-nodejs/cover.png',
    isFree: true,
  },
  'sw-sql': {
    id: 'sw-sql',
    emoji: '🗄️',
    title: 'SQL ครบซัก',
    fullTitle: 'SQL ครบซัก — Joins, Window Functions, Index, Transactions',
    subtitle: 'SELECT → JOIN → Aggregate → Window → CTE → Index → PostgreSQL',
    desc: 'เรียน SQL สำหรับ Dev ครบ JOIN, Window Functions, CTE, Subqueries, Index, Transactions และ PostgreSQL Advanced',
    level: 'เริ่มต้น-กลาง',
    levelColor: '#336791',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['SQL', 'PostgreSQL', 'JOIN', 'Window Functions', 'CTE', 'Index'],
    dataFile: 'sw-sql',
    cover: '/images/sw-sql/cover.png',
    isFree: true,
  },
  'sw-nosql-cache': {
    id: 'sw-nosql-cache',
    emoji: '🍏',
    title: 'MongoDB & Redis',
    fullTitle: 'MongoDB & Redis — NoSQL, Aggregation, Caching, Pub/Sub',
    subtitle: 'MongoDB → Mongoose → Aggregation → Redis → Caching → Pub/Sub',
    desc: 'เรียน MongoDB ด้วย Mongoose, Aggregation Pipeline และ Redis สำหรับ Caching, Session, Pub/Sub, Rate Limiting',
    level: 'กลาง',
    levelColor: '#47a248',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['MongoDB', 'Mongoose', 'Redis', 'Caching', 'NoSQL', 'Pub/Sub'],
    dataFile: 'sw-nosql-cache',
    cover: '/images/sw-nosql-cache/cover.png',
    isFree: true,
  },
  'sw-auth-security': {
    id: 'sw-auth-security',
    emoji: '🔒',
    title: 'Auth & Security',
    fullTitle: 'Authentication & Security — JWT, OAuth2, OWASP, HTTPS',
    subtitle: 'Hashing → JWT → OAuth2 → OWASP → API Security → HTTPS',
    desc: 'เรียน Authentication และ Web Security ครบ JWT, OAuth2, OWASP Top 10, API Security, HTTPS, พร้อม Build Secure Auth System จริง',
    level: 'กลาง',
    levelColor: '#f43f5e',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['JWT', 'OAuth2', 'OWASP', 'bcrypt', 'HTTPS', 'Security'],
    dataFile: 'sw-auth-security',
    cover: '/images/sw-auth-security/cover.png',
    isFree: true,
  },
  'sw-flutter': {
    id: 'sw-flutter',
    emoji: '💧',
    title: 'Flutter จากศูนย์',
    fullTitle: 'Flutter จากศูนย์ — Widgets, Navigation, Firebase, Deploy',
    subtitle: 'Dart → Widgets → Navigation → HTTP → Firebase → App Store',
    desc: 'สร้าง App iOS+Android ด้วย Flutter ตั้งแต่ต้น Widgets, Navigation, HTTP, Firebase Auth, Firestore จนถึง Deploy ขึ้น App Store จริง',
    level: 'เริ่มต้น-กลาง',
    levelColor: '#54c5f8',
    chapterCount: 16,
    duration: '~6 ชม.',
    tags: ['Flutter', 'Dart', 'Firebase', 'iOS', 'Android', 'Mobile'],
    dataFile: 'sw-flutter',
    cover: '/images/sw-flutter/cover.png',
    isFree: true,
  },
  'sw-flutter-state': {
    id: 'sw-flutter-state',
    emoji: '📊',
    title: 'Flutter State Management',
    fullTitle: 'Flutter State Management — Provider, Riverpod, BLoC',
    subtitle: 'Provider → Riverpod → BLoC → Global State → Testing',
    desc: 'เรียน State Management ใน Flutter Provider, Riverpod 2.0, BLoC Pattern และวิธีเลือกที่ถูกสำหรับแต่ละสถานการณ์',
    level: 'กลาง',
    levelColor: '#02569b',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['Flutter', 'Provider', 'Riverpod', 'BLoC', 'State Management'],
    dataFile: 'sw-flutter-state',
    cover: '/images/sw-flutter-state/cover.png',
    isFree: true,
  },
  'sw-docker': {
    id: 'sw-docker',
    emoji: '🐳',
    title: 'Docker ตั้งแต่ต้น',
    fullTitle: 'Docker ตั้งแต่ต้น — Container, Compose, Registry, Production',
    subtitle: 'Container → Dockerfile → Compose → Registry → Production',
    desc: 'เรียน Docker ตั้งแต่ต้น Dockerfile, Docker Compose, Networking, Volumes จนถึง Production Best Practices',
    level: 'กลาง',
    levelColor: '#1d63ed',
    chapterCount: 12,
    duration: '~4 ชม.',
    tags: ['Docker', 'Container', 'Docker Compose', 'DevOps', 'CI/CD'],
    dataFile: 'sw-docker',
    cover: '/images/sw-docker/cover.png',
    isFree: true,
  },
  'sw-cicd': {
    id: 'sw-cicd',
    emoji: '🔄',
    title: 'CI/CD GitHub Actions',
    fullTitle: 'CI/CD ด้วย GitHub Actions — Test, Build, Deploy Automation',
    subtitle: 'Workflow → Testing → Build → Deploy → Secrets → Quality',
    desc: 'สร้าง CI/CD Pipeline ด้วย GitHub Actions Auto Test, Build, Deploy, Code Quality Gates และ Team PR Workflow',
    level: 'กลาง',
    levelColor: '#2088ff',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['CI/CD', 'GitHub Actions', 'Automation', 'DevOps', 'Testing'],
    dataFile: 'sw-cicd',
    cover: '/images/sw-cicd/cover.png',
    isFree: true,
  },
  'sw-aws': {
    id: 'sw-aws',
    emoji: '☁️',
    title: 'AWS สำหรับ Dev',
    fullTitle: 'AWS สำหรับ Dev — EC2, S3, RDS, Lambda, ECS, CloudFront',
    subtitle: 'EC2 → S3 → RDS → Lambda → ECS → CloudFront → IaC',
    desc: 'เรียน AWS สำหรับ Developer EC2, S3, RDS, Lambda, API Gateway, ECS Fargate, CloudFront จนถึง Deploy Full-Stack App บน AWS จริง',
    level: 'กลาง',
    levelColor: '#ff9900',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['AWS', 'EC2', 'S3', 'Lambda', 'ECS', 'CloudFront', 'IaC'],
    dataFile: 'sw-aws',
    cover: '/images/sw-aws/cover.png',
    isFree: true,
  },
  'sw-linux-k8s': {
    id: 'sw-linux-k8s',
    emoji: '🐧',
    title: 'Linux & Kubernetes',
    fullTitle: 'Linux และ Kubernetes — Shell, Server, Pods, Deploy',
    subtitle: 'Linux → Shell Script → Nginx → K8s → Helm → Deploy',
    desc: 'เรียน Linux สำหรับ Dev Shell Script, Server Management และ Kubernetes Pods, Services, Ingress, Helm Charts',
    level: 'กลาง-สูง',
    levelColor: '#fcc624',
    chapterCount: 12,
    duration: '~4 ชม.',
    tags: ['Linux', 'Kubernetes', 'Shell', 'Helm', 'DevOps', 'Nginx'],
    dataFile: 'sw-linux-k8s',
    cover: '/images/sw-linux-k8s/cover.png',
    isFree: true,
  },
  'sw-system-design': {
    id: 'sw-system-design',
    emoji: '🏗️',
    title: 'System Design',
    fullTitle: 'System Design — Load Balancer, Cache, Database, Microservices',
    subtitle: 'Scalability → Cache → DB → Queue → CDN → Microservices',
    desc: 'เรียน System Design สำหรับ Dev Load Balancer, Caching, Database Scaling, Message Queue, CDN และ Design URL Shortener, Twitter Feed, Payment System',
    level: 'สูง',
    levelColor: '#7c3aed',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['System Design', 'Scalability', 'Cache', 'Microservices', 'Interview'],
    dataFile: 'sw-system-design',
    cover: '/images/sw-system-design/cover.png',
    isFree: true,
  },
  'sw-clean-code': {
    id: 'sw-clean-code',
    emoji: '✨',
    title: 'Clean Code & Design Patterns',
    fullTitle: 'Clean Code & Design Patterns — SOLID, GoF, Refactoring',
    subtitle: 'Naming → Functions → SOLID → Creational → Structural → Behavioral',
    desc: 'เรียนเขียน Code ที่ดี SOLID Principles, Design Patterns ทั้ง Creational, Structural, Behavioral และ Refactoring เต็ก Code Smells',
    level: 'กลาง-สูง',
    levelColor: '#f59e0b',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['Clean Code', 'SOLID', 'Design Patterns', 'Refactoring', 'Code Review'],
    dataFile: 'sw-clean-code',
    cover: '/images/sw-clean-code/cover.png',
    isFree: true,
  },
  'sw-microservices': {
    id: 'sw-microservices',
    emoji: '🧩',
    title: 'Microservices Architecture',
    fullTitle: 'Microservices Architecture — DDD, Events, API Gateway, Resilience',
    subtitle: 'DDD → API Gateway → Events → Kafka → Circuit Breaker → Deploy',
    desc: 'เรียน Microservices Architecture ด้วย DDD, Event-Driven, Message Queue, API Gateway, Resilience Patterns จนถึง Split E-commerce Monolith เป็น Services',
    level: 'สูง',
    levelColor: '#ef4444',
    chapterCount: 12,
    duration: '~4 ชม.',
    tags: ['Microservices', 'DDD', 'Event-Driven', 'Kafka', 'API Gateway', 'Docker'],
    dataFile: 'sw-microservices',
    cover: '/images/sw-microservices/cover.png',
    isFree: true,
  },
  'sw-testing': {
    id: 'sw-testing',
    emoji: '🧪',
    title: 'Testing & TDD',
    fullTitle: 'Testing & TDD — Jest, RTL, Playwright, E2E, Coverage',
    subtitle: 'Unit → Integration → E2E → TDD → Coverage → Best Practices',
    desc: 'เรียนเขียน Test ครบ Unit Testing ด้วย Jest, React Testing Library, E2E ด้วย Playwright และ TDD Workflow จริง',
    level: 'กลาง',
    levelColor: '#22c55e',
    chapterCount: 10,
    duration: '~3 ชม.',
    tags: ['Testing', 'Jest', 'React Testing Library', 'Playwright', 'TDD', 'Coverage'],
    dataFile: 'sw-testing',
    cover: '/images/sw-testing/cover.png',
    isFree: true,
  },
  'sw-dsa': {
    id: 'sw-dsa',
    emoji: '🧠',
    title: 'Data Structures & Algorithms',
    fullTitle: 'Data Structures & Algorithms — Arrays, Trees, Graphs, DP',
    subtitle: 'Arrays → Trees → Graphs → DP → Sorting → Interview Strategy',
    desc: 'เรียน DSA ครบ Array, Linked List, Tree, Graph, Heap, DP และ Sorting Algorithms พร้อม Interview Strategy และ LeetCode Patterns',
    level: 'เริ่มต้น-สูง',
    levelColor: '#f43f5e',
    chapterCount: 16,
    duration: '~6 ชม.',
    tags: ['DSA', 'Algorithm', 'LeetCode', 'Trees', 'Graphs', 'Dynamic Programming'],
    dataFile: 'sw-dsa',
    cover: '/images/sw-dsa/cover.png',
    isFree: true,
  },
  'sw-coding-interview': {
    id: 'sw-coding-interview',
    emoji: '🎯',
    title: 'Coding Interview Masterclass',
    fullTitle: 'Coding Interview Masterclass — LeetCode Patterns, Mock Interview',
    subtitle: 'Patterns → DP → System Design → Behavioral → 8-Week Plan',
    desc: 'เรียนเทคนิค LeetCode Patterns และวิธีผ่าน Coding Interview รวม Behavioral Interview และแผนฝึก 8 สัปดาห์',
    level: 'กลาง-สูง',
    levelColor: '#8b5cf6',
    chapterCount: 14,
    duration: '~5 ชม.',
    tags: ['LeetCode', 'Interview', 'Patterns', 'DSA', 'System Design', 'Behavioral'],
    dataFile: 'sw-coding-interview',
    cover: '/images/sw-coding-interview/cover.png',
    isFree: true,
  },
  'sw-junior-roadmap': {
    id: 'sw-junior-roadmap',
    emoji: '🚀',
    title: 'Junior Dev Roadmap',
    fullTitle: 'Junior Dev Roadmap — 6 Month Plan, Portfolio, Job Hunting, Freelance',
    subtitle: 'Roadmap → Portfolio → Resume → Interview → Freelance → Growth',
    desc: 'เส้นทาง 6 เดือนจากศูนย์ถึงงานแรก Portfolio, Resume, Job Hunting ในไทย, Freelance Dev และการเติบโตสู่ Senior',
    level: 'เริ่มต้น',
    levelColor: '#10b981',
    chapterCount: 8,
    duration: '~2 ชม.',
    tags: ['Career', 'Portfolio', 'Resume', 'Job Hunting', 'Freelance', 'Roadmap'],
    dataFile: 'sw-junior-roadmap',
    cover: '/images/sw-junior-roadmap/cover.png',
    isFree: true,
  },
`;

const NEW_META = `  // SW Engineering
  'sw-fundamentals':         { order:  64, group: 'sw', rating: 4.8, students:  920 },
  'sw-git':                  { order:  65, group: 'sw', rating: 4.9, students:  780 },
  'sw-thinking':             { order:  66, group: 'sw', rating: 4.8, students:  650 },
  'sw-html-css':             { order:  67, group: 'sw', rating: 4.9, students: 1150 },
  'sw-javascript':           { order:  68, group: 'sw', rating: 4.9, students: 1340 },
  'sw-javascript-advanced':  { order:  69, group: 'sw', rating: 4.8, students:  720 },
  'sw-react':                { order:  70, group: 'sw', rating: 4.9, students: 1580 },
  'sw-nextjs':               { order:  71, group: 'sw', rating: 4.9, students:  980 },
  'sw-typescript':           { order:  72, group: 'sw', rating: 4.8, students:  850 },
  'sw-python-backend':       { order:  73, group: 'sw', rating: 4.8, students:  760 },
  'sw-fastapi':              { order:  74, group: 'sw', rating: 4.9, students:  680 },
  'sw-nodejs':               { order:  75, group: 'sw', rating: 4.8, students:  920 },
  'sw-sql':                  { order:  76, group: 'sw', rating: 4.9, students: 1100 },
  'sw-nosql-cache':          { order:  77, group: 'sw', rating: 4.8, students:  540 },
  'sw-auth-security':        { order:  78, group: 'sw', rating: 4.9, students:  640 },
  'sw-flutter':              { order:  79, group: 'sw', rating: 4.9, students:  870 },
  'sw-flutter-state':        { order:  80, group: 'sw', rating: 4.8, students:  490 },
  'sw-docker':               { order:  81, group: 'sw', rating: 4.9, students:  820 },
  'sw-cicd':                 { order:  82, group: 'sw', rating: 4.8, students:  580 },
  'sw-aws':                  { order:  83, group: 'sw', rating: 4.8, students:  720 },
  'sw-linux-k8s':            { order:  84, group: 'sw', rating: 4.8, students:  490 },
  'sw-system-design':        { order:  85, group: 'sw', rating: 4.9, students:  960 },
  'sw-clean-code':           { order:  86, group: 'sw', rating: 4.9, students:  750 },
  'sw-microservices':        { order:  87, group: 'sw', rating: 4.9, students:  480 },
  'sw-testing':              { order:  88, group: 'sw', rating: 4.8, students:  560 },
  'sw-dsa':                  { order:  89, group: 'sw', rating: 4.9, students: 1280 },
  'sw-coding-interview':     { order:  90, group: 'sw', rating: 4.9, students: 1450 },
  'sw-junior-roadmap':       { order:  91, group: 'sw', rating: 4.9, students:  890 },
`;

try {
  // Update data/courses-registry.js
  const regPath = 'data/courses-registry.js';
  let regContent = fs.readFileSync(regPath, 'utf-8');
  
  if (!regContent.includes("'sw-fundamentals': {")) {
    const lastIdx = regContent.lastIndexOf('};');
    regContent = regContent.substring(0, lastIdx) + SW_COURSES_REGISTRY + regContent.substring(lastIdx);
    fs.writeFileSync(regPath, regContent, 'utf-8');
    console.log('Updated courses-registry.js');
  } else {
    console.log('courses-registry.js already updated');
  }

  // Update app/courses/page.js
  const pagePath = 'app/courses/page.js';
  let pageContent = fs.readFileSync(pagePath, 'utf-8');
  
  if (!pageContent.includes("'sw-fundamentals':")) {
    pageContent = pageContent.replace(
      "  'lazada-ads-pro':         { order: 63, group: 'ecom', rating: 4.8, students:  540 },\\n};",
      "  'lazada-ads-pro':         { order: 63, group: 'ecom', rating: 4.8, students:  540 },\\n" + NEW_META + "};"
    );
    
    pageContent = pageContent.replace(
      "  { key: 'ecom', label: 'E-Commerce' },\\n];",
      "  { key: 'ecom', label: 'E-Commerce' },\\n  { key: 'sw',   label: 'Software Dev' },\\n];"
    );
    
    pageContent = pageContent.replace(
      "  ecom: { label: '🛒 E-Commerce', color: '#ef4444' },\\n};",
      "  ecom: { label: '🛒 E-Commerce', color: '#ef4444' },\\n  sw:   { label: '💻 Software Dev', color: '#6366f1' },\\n};"
    );
    
    fs.writeFileSync(pagePath, pageContent, 'utf-8');
    console.log('Updated page.js');
  } else {
    console.log('page.js already updated');
  }
} catch (e) {
  console.error(e);
}
