#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
expand_portfolio.py
Generates an expanded de-portfolio.js file (60KB+) with 10 chapters,
each 3000+ characters of rich content.

FORMAT RULES:
- Single-quoted JS strings ONLY (no backticks)
- Escape apostrophes as \'
- Newlines as \n literal
- HTML entities for < > &
- Each chapter object on ONE LONG LINE
- tip-box: <div class=\'tip-box\'><strong>💡</strong> text</div>
"""

import os

OUTPUT_PATH = r"d:\AI\ขาย\de-course\data\courses\de-portfolio.js"

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def esc(text: str) -> str:
    """Escape apostrophes for JS single-quoted strings (backtick-free)."""
    return text.replace("'", "\\'")


def tip(msg: str) -> str:
    return f"<div class=\\'tip-box\\'><strong>💡</strong> {msg}</div>"


def build_chapter(number: int, slug: str, emoji: str, title: str, content: str) -> str:
    """Return one chapter object as a single long JS line."""
    safe_content = esc(content)
    safe_title = esc(title)
    return (
        f"  {{ number: {number}, slug: '{slug}', emoji: '{emoji}', "
        f"title: '{safe_title}', content: '{safe_content}' }}"
    )


# ---------------------------------------------------------------------------
# Chapter content builders
# ---------------------------------------------------------------------------

def ch0_overview() -> str:
    return (
        "<h2>ทำไม Portfolio สำคัญกว่า Certification ในปี 2024</h2>"
        "<p>ในวงการ Data Engineering คำถามที่พบบ่อยที่สุดจาก Career Switcher และ Junior DE คือ: "
        "ควรสอบ AWS Certified Data Analytics, Google Professional Data Engineer, หรือ Databricks Certified Data Engineer ก่อน "
        "หรือควรทำ Portfolio ก่อน? คำตอบที่ชัดเจนและได้รับการพิสูจน์จากประสบการณ์จริงคือ Portfolio สำคัญกว่ามาก</p>"
        "<h3>กระบวนการ Hiring ใน Tech Company ทั่วไป</h3>"
        "<p>เพื่อเข้าใจว่าทำไม Portfolio ถึงสำคัญ ต้องเข้าใจ Hiring Process ก่อน โดยทั่วไปมี 4 ขั้นตอน:</p>"
        "<p><strong>ขั้นที่ 1 - ATS (Applicant Tracking System):</strong> ระบบ Software ที่ Scan Resume "
        "และกรองผู้สมัครด้วย Keywords อัตโนมัติ ATS จะมองหา Skills Keywords เช่น Apache Airflow, dbt, BigQuery, "
        "Python, SQL, Spark, Kafka ถ้า Resume ไม่มี Keywords เหล่านี้จะถูก Filter ออกก่อนที่มนุษย์จะเห็น</p>"
        "<p><strong>ขั้นที่ 2 - Recruiter Review:</strong> Recruiter ใช้เวลา 7-15 วินาที Scan Resume "
        "เพื่อดูว่า Candidate มี Background ที่ Relevant หรือไม่ สิ่งแรกที่ Recruiter มักทำคือ Google ชื่อ "
        "และดู GitHub/LinkedIn ถ้า GitHub ดูดีมี Active Projects จะช่วยให้ผ่านขั้นนี้ได้</p>"
        "<p><strong>ขั้นที่ 3 - Technical Screen:</strong> นัด Call กับ Engineer เพื่อ Assess Technical Skills "
        "ในขั้นนี้ Engineer จะถามเกี่ยวกับ Project ใน Portfolio โดยตรง การมี Portfolio ที่ดีทำให้มี Story ที่น่าสนใจเล่า</p>"
        "<p><strong>ขั้นที่ 4 - Hiring Manager Interview:</strong> Final Interview กับ Manager "
        "ที่จะตัดสินใจ Hire ในขั้นนี้จะถาม Impact และ Business Value ที่สร้างได้จาก Portfolio Projects</p>"
        "<h3>ตารางเปรียบเทียบ: สิ่งที่แต่ละ Stakeholder มองหา</h3>"
        "<p><strong>ATS:</strong> Keywords ตรง JD | Python SQL Airflow dbt Spark Kafka BigQuery Snowflake "
        "| ใส่ Keywords จาก JD ทุกตำแหน่ง</p>"
        "<p><strong>Recruiter:</strong> First Impression GitHub | Projects ที่มี Stars, Good README, Active | "
        "Profile ที่ดูมืออาชีพ</p>"
        "<p><strong>Technical:</strong> Technical Depth | Design Decisions, Trade-offs, Testing | "
        "อธิบาย Why ได้ ไม่ใช่แค่ How</p>"
        "<p><strong>Hiring Manager:</strong> Business Impact | ลด Cost, เพิ่ม Speed, แก้ Real Problem | "
        "Quantify ผลลัพธ์เป็นตัวเลข</p>"
        + tip("อ่าน JD ให้ละเอียดแล้วทำ Portfolio ที่ตอบ Pain Point ของบริษัทนั้นโดยตรง") +
        "<h3>Portfolio vs Certification: Cost-Benefit Analysis</h3>"
        "<p>มาคิดเรื่องนี้อย่างเป็นระบบ:</p>"
        "<p><strong>Certification (เช่น Google Professional Data Engineer):</strong></p>"
        "<p>ค่าสอบ: $200 USD (~7,000 บาท) | เวลาเตรียมสอบ: 2-3 เดือน | "
        "อายุ Certification: 2 ปีต้องต่ออายุ | ผลต่อ Resume: เพิ่ม Credibility บางส่วน | "
        "ผลต่อ Interview: น้อยมาก ช่วยแค่ขั้น ATS</p>"
        "<p><strong>Portfolio Project (E2E Pipeline):</strong></p>"
        "<p>ค่าใช้จ่าย: ~$0-50/เดือน (Free Tier + Cloud) | เวลา: 2-3 เดือน | "
        "อายุ: ตลอดไป สามารถอัปเดตได้ | ผลต่อ Resume: แสดง Real Skill | "
        "ผลต่อ Interview: สูงมาก มี Story เล่าในทุกขั้นตอน</p>"
        "<h3>Certification Value Map</h3>"
        "<p>Certification ที่มีคุณค่ามากที่สุดสำหรับ DE:</p>"
        "<p><strong>Google Professional Data Engineer:</strong> คุ้มค่ามากถ้าสมัคร GCP Companies | "
        "เตรียม 2-3 เดือน | ราคา $200</p>"
        "<p><strong>dbt Analytics Engineering Cert:</strong> มีคุณค่าสูง Market ต้องการมาก | "
        "เตรียม 1-2 เดือน | ราคา $200</p>"
        "<p><strong>Apache Airflow Certification:</strong> คุ้มค่าปานกลาง | เตรียม 1 เดือน | ราคา $250</p>"
        "<p><strong>AWS Data Analytics Specialty:</strong> คุ้มค่าถ้าสมัคร AWS Companies | "
        "เตรียม 3 เดือน | ราคา $300</p>"
        "<p><strong>Databricks Certified DE Associate:</strong> คุ้มค่าสูงในบริษัทที่ใช้ Databricks | "
        "เตรียม 1-2 เดือน | ราคา $200</p>"
        + tip("ลำดับที่แนะนำ: สร้าง Portfolio ก่อน แล้วค่อยสอบ Certification เพื่อเสริมความน่าเชื่อถือ") +
        "<h3>Portfolio ROI Calculation</h3>"
        "<p>ลองคำนวณ ROI ของการทำ Portfolio: สมมติใช้เวลา 3 เดือน (12 สัปดาห์) ทำ Portfolio "
        "และได้งาน Data Engineer ที่ได้เงินเดือน 80,000 บาท (จากเดิม 40,000 บาท) "
        "นั่นหมายถึง ROI ปีแรก = (40,000 x 12) / ค่าใช้จ่าย = 480,000 / 1,500 = 32,000% ROI!</p>"
        "<h3>กลยุทธ์ 12 สัปดาห์สร้าง Portfolio ขณะทำงานประจำ</h3>"
        "<p>สัปดาห์ 1-2: Setup Environment (GitHub, Docker, Cloud Account) และวางแผน Project</p>"
        "<p>สัปดาห์ 3-4: สร้าง Ingestion Layer (Python scripts + Airflow DAGs)</p>"
        "<p>สัปดาห์ 5-6: สร้าง Storage Layer (Data Lake + Data Warehouse)</p>"
        "<p>สัปดาห์ 7-8: สร้าง Transformation Layer (dbt models + tests)</p>"
        "<p>สัปดาห์ 9-10: สร้าง Serving Layer (Dashboard) + Monitoring</p>"
        "<p>สัปดาห์ 11: Documentation (README + Architecture Diagram + ADRs)</p>"
        "<p>สัปดาห์ 12: Polish + GitHub Profile + LinkedIn Update + เริ่มสมัครงาน</p>"
        + tip("ลง Calendar Blocking 2 ชั่วโมง/วัน ช่วงเย็นหรือเช้า และทำทุกวันไม่ขาด ความสม่ำเสมอสำคัญที่สุด")
    )


def ch1_github() -> str:
    return (
        "<h2>GitHub Profile: หน้าต่างแรกที่ Recruiter เห็น</h2>"
        "<p>GitHub Profile คือ Digital Resume ที่สำคัญที่สุดของ Data Engineer ทุกคน "
        "เมื่อ Recruiter สนใจ Resume ของคุณ สิ่งแรกที่ทำคือ Click ที่ GitHub Link "
        "ถ้า Profile ดูดีและ Professional จะเพิ่มโอกาสได้ Interview อย่างมาก "
        "บทนี้จะ Cover ทุกอย่างตั้งแต่ Profile README ไปจนถึง Contribution Graph</p>"
        "<h3>GitHub Profile README: Template สมบูรณ์</h3>"
        "<p>สร้าง Repository ชื่อเดียวกับ GitHub Username ของคุณ (เช่น github.com/yourname/yourname) "
        "แล้วสร้างไฟล์ README.md ด้านล่างคือ Template ที่แนะนำ:</p>"
        "<pre><code>"
        "# Hi, I&apos;m [Your Name] 👋\n"
        "\n"
        "## 🔧 Data Engineer | Python • Airflow • dbt • BigQuery\n"
        "\n"
        "I build scalable data pipelines that turn raw data into business insights.\n"
        "Currently working on [Current Project] and exploring [New Tech].\n"
        "\n"
        "### 🛠️ Tech Stack\n"
        "\n"
        "**Orchestration:** Apache Airflow • Prefect\n"
        "**Transformation:** dbt • PySpark\n"
        "**Storage:** BigQuery • Snowflake • PostgreSQL • S3\n"
        "**Streaming:** Apache Kafka • Kinesis\n"
        "**Languages:** Python • SQL • Bash\n"
        "**IaC:** Terraform • Docker • GitHub Actions\n"
        "\n"
        "### 📊 GitHub Stats\n"
        "\n"
        "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=YOUR_USERNAME&amp;show_icons=true&amp;theme=dark)\n"
        "![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=YOUR_USERNAME&amp;layout=compact&amp;theme=dark)\n"
        "\n"
        "### 🌱 Currently Learning\n"
        "- Apache Flink for real-time processing\n"
        "- Rust for high-performance data tools\n"
        "\n"
        "### 📫 Connect with me\n"
        "- LinkedIn: [your-profile](https://linkedin.com/in/yourname)\n"
        "- Email: your@email.com\n"
        "</code></pre>"
        + tip("ใช้ shields.io เพื่อสร้าง Badge ที่ดูดี เช่น Build Status, License, Python Version") +
        "<h3>github-readme-stats Setup</h3>"
        "<p>Fork ไปที่ github.com/anuraghazra/github-readme-stats แล้ว Deploy บน Vercel ฟรี "
        "หรือใช้ Public Instance ได้เลย แต่อาจช้าเพราะ Rate Limit เพิ่ม Parameters เหล่านี้ได้: "
        "show_icons=true, theme=dark หรือ radical, hide_border=true, count_private=true, "
        "include_all_commits=true</p>"
        "<h3>Shields.io Badges สำหรับ DE Tools</h3>"
        "<p>ใส่ Badges เหล่านี้ใน README ของแต่ละ Project:</p>"
        "<p>Python Version: ![Python](https://img.shields.io/badge/Python-3.11-blue)</p>"
        "<p>Apache Airflow: ![Airflow](https://img.shields.io/badge/Airflow-2.8-017CEE)</p>"
        "<p>dbt: ![dbt](https://img.shields.io/badge/dbt-1.7-FF694B)</p>"
        "<p>BigQuery: ![BigQuery](https://img.shields.io/badge/BigQuery-Google-4285F4)</p>"
        "<p>Docker: ![Docker](https://img.shields.io/badge/Docker-24.0-2496ED)</p>"
        "<p>Build Status: ![CI](https://github.com/user/repo/actions/workflows/ci.yml/badge.svg)</p>"
        "<h3>Topics/Tags Best Practices</h3>"
        "<p>ใส่ Topics ใน Repository Settings ให้ครบ เพราะ GitHub ใช้ Topics ในการ Search: "
        "data-engineering, apache-airflow, dbt, bigquery, python, etl, data-pipeline, "
        "apache-spark, kafka, postgresql, docker, github-actions, data-warehouse, data-lake</p>"
        "<h3>Commit Message Conventions</h3>"
        "<p>ใช้ Conventional Commits format เพื่อ Commit History ที่สะอาด:</p>"
        "<p>feat: add crypto price ingestion DAG</p>"
        "<p>fix: handle missing values in price data</p>"
        "<p>docs: update README with architecture diagram</p>"
        "<p>test: add unit tests for transformation functions</p>"
        "<p>refactor: extract common DB connection to utils</p>"
        "<p>chore: update dependencies to latest versions</p>"
        "<p>perf: optimize BigQuery query with partition pruning</p>"
        + tip("ติดตั้ง commitlint + husky เพื่อ Enforce Commit Convention อัตโนมัติ") +
        "<h3>.gitignore Template สำหรับ DE Projects</h3>"
        "<p>สิ่งที่ต้อง Ignore เสมอ: .env, *.env.local, secrets/, credentials.json, "
        "service-account-key.json, __pycache__/, *.pyc, .venv/, venv/, "
        ".DS_Store, *.log, logs/, target/ (dbt), dbt_packages/, "
        ".airflow/, airflow.db, airflow.cfg</p>"
        "<h3>GitHub Actions CI/CD Template</h3>"
        "<p>สร้างไฟล์ .github/workflows/ci.yml เพื่อรัน Tests อัตโนมัติ:</p>"
        "<pre><code>"
        "name: CI Pipeline\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v4\n"
        "        with:\n"
        "          python-version: &apos;3.11&apos;\n"
        "      - run: pip install -r requirements.txt\n"
        "      - run: pytest tests/ -v\n"
        "      - run: dbt compile --profiles-dir .\n"
        "</code></pre>"
        "<h3>Green Contribution Graph Tips</h3>"
        "<p>วิธีทำให้ Contribution Graph เป็นสีเขียวสม่ำเสมอ: Commit ทุกวัน แม้แค่แก้ Typo หรือเพิ่ม Comment, "
        "สร้าง Learning Log Repository สำหรับ Note สิ่งที่เรียนแต่ละวัน, "
        "ทำ Advent of Code ปีละครั้ง, มีส่วนร่วมใน Open Source แม้แค่ Fix Typo ใน Documentation, "
        "ตั้ง Daily Reminder เพื่อไม่ให้ลืม Commit</p>"
        "<h3>Archived vs Active Repos</h3>"
        "<p>Archive Repository ที่ไม่ได้ใช้แล้วเพื่อให้ Profile ดูสะอาดและ Professional: "
        "Active = Pinned 6 Projects ที่ดีที่สุด | Archived = Tutorial projects เก่า, "
        "Incomplete experiments | Delete = repos ที่ empty หรือ fork ที่ไม่ได้ใช้</p>"
    )


def ch2_project_ideas() -> str:
    return (
        "<h2>10 Project Ideas ระดับ Professional สำหรับ DE Portfolio</h2>"
        "<p>การเลือก Project ที่ถูกต้องคือกุญแจสำคัญในการสร้าง Portfolio ที่ได้งาน "
        "Project ต้องแสดงทักษะที่ Industry ต้องการ ใช้ Tech Stack ที่ทันสมัย "
        "และมีความซับซ้อนพอสมควรที่แสดงให้เห็น Problem-solving Skills</p>"
        "<h3>ตาราง 10 Project Ideas</h3>"
        "<p><strong>1. Real-time Crypto Pipeline</strong></p>"
        "<p>Architecture: Lambda/Streaming | Tech: Kafka + Flink/Spark Streaming + TimescaleDB + Grafana | "
        "Data Source: Binance API, CoinGecko | เวลา: 6-8 สัปดาห์ | ความยาก: Hard | "
        "Skills: Streaming, Real-time Analytics, Time-series DB</p>"
        "<p>Description: ดึงราคา Cryptocurrency จาก Binance WebSocket API แบบ Real-time "
        "ผ่าน Kafka Topic แล้วประมวลผลด้วย Flink หรือ Spark Structured Streaming "
        "คำนวณ Moving Averages, RSI, MACD แล้วเก็บใน TimescaleDB และ Visualize ด้วย Grafana "
        "พร้อม Alert เมื่อราคาเปลี่ยนเกิน 5% ใน 1 นาที</p>"
        "<p><strong>2. E-commerce Analytics Platform</strong></p>"
        "<p>Architecture: Medallion (Bronze/Silver/Gold) | Tech: Airflow + dbt + BigQuery + Looker Studio | "
        "Data Source: Faker Library (synthetic) | เวลา: 4-6 สัปดาห์ | ความยาก: Medium | "
        "Skills: Batch ETL, Data Modeling, SQL Optimization, Dashboard</p>"
        "<p>Description: จำลองระบบ E-commerce ด้วย Python Faker สร้าง 1M+ Orders "
        "Airflow DAG ดึงข้อมูลทุกวัน เก็บ Raw ใน GCS (Bronze) Transform ใน BigQuery (Silver) "
        "สร้าง dbt Models สำหรับ Revenue by Category, Customer LTV, Cohort Analysis (Gold) "
        "Dashboard แสดง Real-time Metrics</p>"
        "<p><strong>3. Weather Analytics & Forecasting</strong></p>"
        "<p>Architecture: Batch + ML | Tech: Airflow + Python + PostgreSQL + Superset | "
        "Data Source: Open-Meteo API (free, no key) | เวลา: 3-4 สัปดาห์ | ความยาก: Easy-Medium | "
        "Skills: API Ingestion, Time-series Analysis, Simple ML Integration</p>"
        "<p>Description: ดึงข้อมูลสภาพอากาศ 50 เมืองทั่วโลกจาก Open-Meteo API ทุก 6 ชั่วโมง "
        "เก็บใน PostgreSQL สร้าง dbt Models วิเคราะห์ Temperature Trend, Anomaly Detection "
        "รัน Simple Prophet Forecast และแสดงผลใน Apache Superset</p>"
        "<p><strong>4. Social Media Analytics Pipeline</strong></p>"
        "<p>Architecture: Batch | Tech: Airflow + Python + Spark + BigQuery | "
        "Data Source: Reddit API, YouTube Data API | เวลา: 4-5 สัปดาห์ | ความยาก: Medium | "
        "Skills: API Integration, NLP, Sentiment Analysis, Trend Detection</p>"
        "<p>Description: ดึงโพสต์จาก Reddit r/datascience ทุกชั่วโมง รัน Sentiment Analysis "
        "ด้วย HuggingFace Transformers วิเคราะห์ Trending Topics และ Top Contributors "
        "ค้นพบ Patterns ว่า Post ประเภทไหนได้รับ Upvotes มากที่สุด</p>"
        "<p><strong>5. Data Quality Monitoring Framework</strong></p>"
        "<p>Architecture: Batch + Monitoring | Tech: Great Expectations + Airflow + dbt + Slack API | "
        "Data Source: Any existing dataset | เวลา: 3-4 สัปดาห์ | ความยาก: Medium | "
        "Skills: Data Quality, Alerting, Observability, dbt Tests</p>"
        "<p>Description: Framework ที่รัน Data Quality Checks อัตโนมัติทุกวัน "
        "ตรวจสอบ Completeness, Freshness, Uniqueness, Validity ของข้อมูล "
        "ส่ง Alert ผ่าน Slack เมื่อ Data Quality ต่ำกว่า Threshold "
        "สร้าง Dashboard แสดง DQ Score Trend ตามเวลา</p>"
        + tip("Project Data Quality Framework โดดเด่นมากเพราะบริษัทส่วนใหญ่ยังขาดแคลนคนที่ทำเรื่องนี้ได้") +
        "<p><strong>6. Sports Analytics Platform</strong></p>"
        "<p>Architecture: Batch | Tech: Airflow + dbt + BigQuery + Streamlit | "
        "Data Source: TheSportsDB API, football-data.org | เวลา: 4-5 สัปดาห์ | ความยาก: Medium | "
        "Skills: API Ingestion, Advanced SQL, Analytical Dashboard</p>"
        "<p>Description: ดึงข้อมูล Premier League ทุก Match ตั้งแต่ปี 2010 "
        "สร้าง Advanced Analytics เช่น Expected Goals, Player Performance Metrics, "
        "Head-to-Head Statistics, Season Trend Analysis ด้วย dbt "
        "Visualize ด้วย Streamlit ที่ User Interactive ได้</p>"
        "<p><strong>7. Financial Data Pipeline (SEC Filings)</strong></p>"
        "<p>Architecture: Batch | Tech: Airflow + Python + Snowflake + dbt | "
        "Data Source: SEC EDGAR API (free) | เวลา: 5-6 สัปดาห์ | ความยาก: Hard | "
        "Skills: Complex Data Parsing, Financial Modeling, Large Dataset</p>"
        "<p>Description: ดึง Financial Statements จาก SEC EDGAR (10-K, 10-Q filings) "
        "ของ S&amp;P 500 Companies Parse XML/XBRL Format คำนวณ Financial Ratios "
        "เช่น P/E, Debt-to-Equity, Revenue Growth สร้าง Screening Dashboard "
        "หา Undervalued Stocks ด้วย Value Investing Metrics</p>"
        "<p><strong>8. IoT Data Platform (Simulated)</strong></p>"
        "<p>Architecture: Lambda (Batch + Stream) | Tech: MQTT + Kafka + Flink + InfluxDB + Grafana | "
        "Data Source: Python IoT Simulator | เวลา: 6-8 สัปดาห์ | ความยาก: Hard | "
        "Skills: IoT Architecture, Streaming, Time-series, Edge Computing</p>"
        "<p>Description: จำลองโรงงานอุตสาหกรรมด้วย Python MQTT Publisher "
        "ส่ง Sensor Data (Temperature, Pressure, Vibration) ทุก 100ms "
        "ผ่าน Kafka ไปยัง Flink สำหรับ Anomaly Detection แบบ Real-time "
        "เก็บใน InfluxDB และ Alert เมื่อเครื่องจักรใกล้ขัดข้อง</p>"
        "<p><strong>9. Log Analytics Pipeline (ELK-style)</strong></p>"
        "<p>Architecture: Streaming + OLAP | Tech: Filebeat + Kafka + Spark + ClickHouse + Grafana | "
        "Data Source: Generated Nginx/Application Logs | เวลา: 4-5 สัปดาห์ | ความยาก: Medium-Hard | "
        "Skills: Log Parsing, OLAP Database, Streaming, Observability</p>"
        "<p>Description: Pipeline ที่รับ Log จาก Web Application แบบ Real-time "
        "Parse Structured Fields ด้วย Regex สร้าง Aggregation ด้วย Spark "
        "เก็บใน ClickHouse (OLAP Database ที่เร็วมาก) "
        "สร้าง Dashboard แสดง Error Rate, Latency P95/P99, Top Error Messages</p>"
        "<p><strong>10. Wikipedia ETL &amp; Knowledge Graph</strong></p>"
        "<p>Architecture: Batch | Tech: Airflow + Python + Neo4j + Spark | "
        "Data Source: Wikipedia API + Wikidata | เวลา: 5-6 สัปดาห์ | ความยาก: Hard | "
        "Skills: Graph Database, NLP, Large-scale ETL, Knowledge Extraction</p>"
        "<p>Description: ดึงข้อมูล Wikipedia Articles หมวด Technology ทุกสัปดาห์ "
        "Extract Entities และ Relationships ด้วย spaCy NER "
        "สร้าง Knowledge Graph ใน Neo4j ค้นหา Patterns เช่น "
        "บริษัทไหนเชื่อมกันผ่าน Technology หรือ Person บ้าง "
        "Expose ผ่าน GraphQL API</p>"
    )


def ch3_end_to_end() -> str:
    return (
        "<h2>Tutorial: สร้าง End-to-End Data Pipeline แบบ Production-ready</h2>"
        "<p>บทนี้จะ Walk-through การสร้าง E2E Pipeline แบบละเอียด "
        "ที่ครอบคลุมทุก Component ตั้งแต่ Source ไปจนถึง Dashboard "
        "โดยใช้ Stack ที่ใกล้เคียงกับ Production จริงในบริษัทชั้นนำ</p>"
        "<h3>โครงสร้าง GitHub Repository</h3>"
        "<pre><code>"
        "my-de-pipeline/\n"
        "├── .github/\n"
        "│   └── workflows/\n"
        "│       ├── ci.yml\n"
        "│       └── deploy.yml\n"
        "├── src/\n"
        "│   ├── ingestion/\n"
        "│   │   ├── __init__.py\n"
        "│   │   ├── api_client.py\n"
        "│   │   └── extractors.py\n"
        "│   ├── transformations/\n"
        "│   │   └── cleaners.py\n"
        "│   └── utils/\n"
        "│       ├── db.py\n"
        "│       └── logger.py\n"
        "├── dbt/\n"
        "│   ├── models/\n"
        "│   │   ├── staging/\n"
        "│   │   ├── intermediate/\n"
        "│   │   └── marts/\n"
        "│   ├── tests/\n"
        "│   ├── dbt_project.yml\n"
        "│   └── profiles.yml\n"
        "├── airflow/\n"
        "│   └── dags/\n"
        "│       ├── ingestion_dag.py\n"
        "│       └── transform_dag.py\n"
        "├── tests/\n"
        "│   ├── unit/\n"
        "│   └── integration/\n"
        "├── docs/\n"
        "│   ├── architecture.png\n"
        "│   └── adr/\n"
        "├── docker-compose.yml\n"
        "├── Makefile\n"
        "├── requirements.txt\n"
        "└── README.md\n"
        "</code></pre>"
        "<h3>Docker Compose Services</h3>"
        "<p><strong>Airflow Webserver:</strong> apache/airflow:2.8.0 | Port 8080 | "
        "UI สำหรับ Monitor DAGs | Depends on Postgres + Redis</p>"
        "<p><strong>Airflow Scheduler:</strong> apache/airflow:2.8.0 | Background Service | "
        "รัน DAG ตาม Schedule | Core Component</p>"
        "<p><strong>Airflow Worker:</strong> apache/airflow:2.8.0 | Background Service | "
        "Execute Tasks ด้วย CeleryExecutor | Scale ได้</p>"
        "<p><strong>PostgreSQL:</strong> postgres:15 | Port 5432 | "
        "Airflow Metadata DB + Application DB | Persistent Volume</p>"
        "<p><strong>Redis:</strong> redis:7 | Port 6379 | "
        "Celery Broker สำหรับ Task Queue | In-memory</p>"
        "<p><strong>MinIO:</strong> minio/minio | Port 9000/9001 | "
        "S3-compatible Object Storage (Data Lake) | Local Development</p>"
        + tip("MinIO ทำให้ทดสอบ S3 Logic ในเครื่องได้โดยไม่ต้องเสียเงิน AWS จริงๆ") +
        "<h3>ตัวอย่าง Airflow DAG</h3>"
        "<pre><code>"
        "from airflow import DAG\n"
        "from airflow.operators.python import PythonOperator\n"
        "from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator\n"
        "from datetime import datetime, timedelta\n"
        "import pendulum\n"
        "\n"
        "default_args = {\n"
        "    &apos;owner&apos;: &apos;data-engineering&apos;,\n"
        "    &apos;retries&apos;: 3,\n"
        "    &apos;retry_delay&apos;: timedelta(minutes=5),\n"
        "    &apos;email_on_failure&apos;: True,\n"
        "}\n"
        "\n"
        "with DAG(\n"
        "    dag_id=&apos;crypto_pipeline&apos;,\n"
        "    schedule=&apos;@hourly&apos;,\n"
        "    start_date=pendulum.datetime(2024, 1, 1, tz=&apos;UTC&apos;),\n"
        "    default_args=default_args,\n"
        "    catchup=False,\n"
        "    tags=[&apos;crypto&apos;, &apos;production&apos;],\n"
        ") as dag:\n"
        "\n"
        "    extract = PythonOperator(\n"
        "        task_id=&apos;extract_prices&apos;,\n"
        "        python_callable=extract_crypto_prices,\n"
        "    )\n"
        "\n"
        "    load_to_gcs = PythonOperator(\n"
        "        task_id=&apos;load_to_gcs&apos;,\n"
        "        python_callable=upload_to_gcs,\n"
        "    )\n"
        "\n"
        "    load_to_bq = BigQueryInsertJobOperator(\n"
        "        task_id=&apos;load_to_bigquery&apos;,\n"
        "        configuration={&apos;load&apos;: {...}},\n"
        "    )\n"
        "\n"
        "    extract &gt;&gt; load_to_gcs &gt;&gt; load_to_bq\n"
        "</code></pre>"
        "<h3>dbt Project Structure</h3>"
        "<p><strong>Staging Models (stg_*):</strong> 1-to-1 mapping กับ Source Tables "
        "ทำ Type Casting, Renaming, Basic Filtering ไม่มี Business Logic</p>"
        "<p><strong>Intermediate Models (int_*):</strong> Join หลาย Staging Tables "
        "เพิ่ม Business Logic เช่น คำนวณ Revenue, ระบุ Customer Segments</p>"
        "<p><strong>Mart Models (fct_*, dim_*):</strong> Final Tables ที่ Business ใช้ "
        "fct_ สำหรับ Fact Tables (transactions, events) "
        "dim_ สำหรับ Dimension Tables (products, customers, dates)</p>"
        "<h3>dbt Test Types</h3>"
        "<p><strong>Generic Tests (built-in):</strong></p>"
        "<p>not_null: ตรวจ NULL Values | unique: ตรวจ Duplicate | "
        "accepted_values: ตรวจค่าที่ยอมรับได้ | relationships: ตรวจ Foreign Key</p>"
        "<p><strong>Custom Tests:</strong></p>"
        "<p>test_revenue_positive: Revenue ต้องมากกว่า 0 | "
        "test_date_not_future: Date ต้องไม่เป็นอนาคต | "
        "test_row_count_growth: จำนวน Rows ต้องเพิ่มขึ้นทุกวัน</p>"
        "<h3>Makefile Tasks</h3>"
        "<pre><code>"
        "setup: ## Install all dependencies\n"
        "    pip install -r requirements.txt\n"
        "    dbt deps\n"
        "\n"
        "up: ## Start all Docker services\n"
        "    docker-compose up -d\n"
        "\n"
        "test: ## Run all tests\n"
        "    pytest tests/ -v --cov=src\n"
        "    dbt test\n"
        "\n"
        "run: ## Run full pipeline\n"
        "    python src/ingestion/extractors.py\n"
        "    dbt run\n"
        "    dbt test\n"
        "\n"
        "docs: ## Generate dbt documentation\n"
        "    dbt docs generate\n"
        "    dbt docs serve\n"
        "</code></pre>"
        + tip("Makefile ช่วยให้ Interviewer รัน Project ได้ด้วยคำสั่งเดียว ทำให้ impression ดีมาก") +
        "<h3>GitHub Actions CI/CD Workflow</h3>"
        "<p>Workflow ที่ต้องมี: 1) Lint Python code (flake8/ruff) "
        "2) Run unit tests (pytest) 3) dbt compile check "
        "4) Security scan (bandit) 5) (Optional) Deploy to Staging</p>"
        "<h3>Monitoring Setup</h3>"
        "<p>สิ่งที่ต้อง Monitor ใน Production Pipeline: "
        "DAG Run Duration (Alert ถ้านานกว่า SLA), "
        "Task Failure Rate (Alert ทันทีที่ Fail), "
        "Data Freshness (Alert ถ้า Data เก่ากว่า N ชั่วโมง), "
        "Row Count Anomaly (Alert ถ้า Count เปลี่ยนเกิน 20%), "
        "Cost Alert (Alert ถ้า BigQuery Query เกิน Budget)</p>"
    )


def ch4_documentation() -> str:
    return (
        "<h2>Documentation: สร้าง README ที่ทำให้ Project ดูมืออาชีพ</h2>"
        "<p>Documentation ที่ยอดเยี่ยมคือสิ่งที่แยก Portfolio ระดับ Senior ออกจาก Junior "
        "เพราะแสดงว่าคุณคิดถึงคนอื่น มีความใส่ใจในรายละเอียด "
        "และเข้าใจว่าใน Real Project ทีมต้องทำงานร่วมกัน "
        "บทนี้จะ Cover ทุก Aspect ของ Documentation ที่ดี</p>"
        "<h3>Complete README Template</h3>"
        "<pre><code>"
        "# 🚀 Project Name\n"
        "\n"
        "![Build](https://github.com/user/repo/actions/workflows/ci.yml/badge.svg)\n"
        "![Python](https://img.shields.io/badge/Python-3.11-blue)\n"
        "![License](https://img.shields.io/badge/License-MIT-green)\n"
        "\n"
        "&gt; One-line description of what this project does and why it matters.\n"
        "\n"
        "## 📋 Overview\n"
        "Brief 2-3 paragraph explanation of the project.\n"
        "What problem does it solve? What data does it process?\n"
        "\n"
        "## 🏗️ Architecture\n"
        "![Architecture Diagram](docs/architecture.png)\n"
        "\n"
        "### Data Flow\n"
        "1. **Extract**: Pull data from Source API every hour\n"
        "2. **Load**: Store raw data in GCS (Bronze layer)\n"
        "3. **Transform**: dbt models create Silver &amp; Gold layers\n"
        "4. **Serve**: Looker Studio Dashboard for business users\n"
        "\n"
        "## 🛠️ Tech Stack\n"
        "| Component | Technology | Purpose |\n"
        "| --- | --- | --- |\n"
        "| Orchestration | Apache Airflow 2.8 | Schedule &amp; Monitor |\n"
        "| Transformation | dbt 1.7 | SQL Modeling |\n"
        "| Data Warehouse | BigQuery | Analytics Storage |\n"
        "| Data Lake | Google Cloud Storage | Raw Data Storage |\n"
        "| Containerization | Docker + Compose | Local Dev |\n"
        "\n"
        "## ⚡ Quick Start\n"
        "```bash\n"
        "git clone https://github.com/user/repo\n"
        "cp .env.example .env  # Fill in your credentials\n"
        "make setup\n"
        "make up\n"
        "make run\n"
        "```\n"
        "\n"
        "## ⚙️ Configuration\n"
        "| Variable | Description | Required |\n"
        "| --- | --- | --- |\n"
        "| GCP_PROJECT_ID | Google Cloud Project ID | Yes |\n"
        "| BQ_DATASET | BigQuery Dataset Name | Yes |\n"
        "| API_KEY | Source API Key | Yes |\n"
        "\n"
        "## 🧪 Testing\n"
        "```bash\n"
        "make test          # Run all tests\n"
        "pytest tests/unit  # Unit tests only\n"
        "dbt test           # dbt model tests\n"
        "```\n"
        "\n"
        "## 🚀 Deployment\n"
        "See [deployment guide](docs/deployment.md) for production setup.\n"
        "\n"
        "## 🤝 Contributing\n"
        "See [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.\n"
        "</code></pre>"
        + tip("ใส่ Architecture Diagram เป็นรูปภาพจริงในทุก Project README เพราะ Recruiter จะเข้าใจ Project ได้ใน 5 วินาที") +
        "<h3>Mermaid Diagram Syntax</h3>"
        "<p>GitHub รองรับ Mermaid Diagrams ใน Markdown โดยตรง ไม่ต้องใช้รูปภาพ:</p>"
        "<pre><code>"
        "```mermaid\n"
        "graph LR\n"
        "    A[CoinGecko API] --&gt;|HTTP Request| B[Python Extractor]\n"
        "    B --&gt;|Raw JSON| C[GCS Bronze]\n"
        "    C --&gt;|Airflow DAG| D[BigQuery Staging]\n"
        "    D --&gt;|dbt run| E[BigQuery Marts]\n"
        "    E --&gt;|Looker Studio| F[Dashboard]\n"
        "```\n"
        "</code></pre>"
        "<h3>ADR (Architecture Decision Record) Template</h3>"
        "<p>ADR คือ Document ที่บันทึกการตัดสินใจทาง Architecture สร้างใน docs/adr/ "
        "ตั้งชื่อไฟล์เป็น 001-use-bigquery-over-redshift.md</p>"
        "<p><strong>ADR Structure:</strong></p>"
        "<p>Title: ADR-001: ใช้ BigQuery แทน Redshift</p>"
        "<p>Status: Accepted</p>"
        "<p>Date: 2024-01-15</p>"
        "<p>Context: ต้องเลือก Data Warehouse สำหรับโปรเจกต์ที่ใช้ GCP Stack</p>"
        "<p>Decision: เลือก BigQuery เพราะ Serverless, Free Tier 1TB/month, "
        "Integration กับ GCS ดีกว่า, ไม่ต้อง Manage Cluster</p>"
        "<p>Consequences: ข้อดี - ไม่มีค่า Cluster, SQL Standard, Fast | "
        "ข้อเสีย - Vendor Lock-in กับ GCP, บาง SQL Syntax ต่างจาก Standard</p>"
        "<h3>Data Dictionary Template</h3>"
        "<p>ทุก Table ใน Data Warehouse ควรมี Data Dictionary:</p>"
        "<p>Table: fct_orders | Description: Transaction-level order data | "
        "Grain: One row per order | Update frequency: Daily</p>"
        "<p>Column: order_id | Type: STRING | Description: Unique order identifier | "
        "Not Null: Yes | Example: ORD-2024-001234</p>"
        "<p>Column: order_date | Type: DATE | Description: Date order was placed | "
        "Not Null: Yes | Example: 2024-01-15</p>"
        "<h3>Semantic Versioning สำหรับ Data Projects</h3>"
        "<p>ใช้ Git Tags และ Changelog เพื่อ Track Version ของ Pipeline: "
        "MAJOR.MINOR.PATCH เช่น v2.1.3</p>"
        "<p>MAJOR: Breaking change ใน Schema หรือ API | "
        "MINOR: New Feature หรือ New Model | "
        "PATCH: Bug fix หรือ Performance improvement</p>"
        "<h3>MkDocs Setup สำหรับ Documentation Site</h3>"
        "<p>สร้าง Documentation Website ด้วย MkDocs + Material Theme: "
        "pip install mkdocs mkdocs-material | "
        "mkdocs new . | "
        "mkdocs serve (local preview) | "
        "mkdocs gh-deploy (deploy ไปยัง GitHub Pages ฟรี)</p>"
    )


def ch5_data_sources() -> str:
    return (
        "<h2>Free Data Sources: คลังข้อมูลสำหรับ Portfolio Project</h2>"
        "<p>หนึ่งในอุปสรรคใหญ่ที่สุดของมือใหม่คือการหาข้อมูลที่น่าสนใจ มีคุณภาพ "
        "และใหญ่พอที่จะแสดงทักษะ Data Engineering บทนี้รวบรวม 25+ Free Data Sources "
        "พร้อม Tips การใช้งาน API Limits และ Project Ideas</p>"
        "<h3>Public APIs (Real-time Data)</h3>"
        "<p><strong>Open-Meteo (openmeteo.com):</strong> "
        "ข้อมูลสภาพอากาศ Historical + Forecast | ไม่ต้อง API Key | "
        "Rate Limit: 10,000 requests/day | Project Idea: Weather Analytics Dashboard</p>"
        "<p><strong>CoinGecko (api.coingecko.com):</strong> "
        "ราคา Cryptocurrency 12,000+ coins | Free Plan 30 calls/min | "
        "Rate Limit: 10-50 calls/min | Project Idea: Crypto Portfolio Tracker</p>"
        "<p><strong>Reddit API (reddit.com/r/...):</strong> "
        "โพสต์ Comments ข้อมูล Community | OAuth2 Required | "
        "Rate Limit: 60 req/min | Project Idea: Sentiment Analysis Pipeline</p>"
        "<p><strong>GitHub REST API:</strong> "
        "Repository Commits Issues Stars | Personal Token | "
        "Rate Limit: 5,000 req/hour | Project Idea: Developer Activity Analytics</p>"
        "<p><strong>REST Countries (restcountries.com):</strong> "
        "ข้อมูลประเทศ Population GDP | ไม่ต้อง Auth | "
        "Rate Limit: Unlimited | Project Idea: Geographic Data Dashboard</p>"
        "<p><strong>TheSportsDB (thesportsdb.com):</strong> "
        "ข้อมูลกีฬา Football, Basketball | Free Key | "
        "Rate Limit: ปานกลาง | Project Idea: Sports Analytics Platform</p>"
        "<p><strong>NASA APIs (api.nasa.gov):</strong> "
        "APOD, Mars Weather, NEO Asteroids | Free Key | "
        "Rate Limit: 1,000 req/hour | Project Idea: Space Data Dashboard</p>"
        "<p><strong>Alpha Vantage (alphavantage.co):</strong> "
        "หุ้น Forex Crypto | Free Key | "
        "Rate Limit: 25 req/day (free) | Project Idea: Stock Market Analytics</p>"
        "<p><strong>OpenFDA (api.fda.gov):</strong> "
        "ข้อมูลยาและ Drug Events | ไม่ต้อง Key | "
        "Rate Limit: 240 req/min | Project Idea: Healthcare Data Pipeline</p>"
        "<p><strong>Spotify Web API:</strong> "
        "เพลง Artist Audio Features | OAuth2 | "
        "Rate Limit: Variable | Project Idea: Music Trend Analytics</p>"
        + tip("Open-Meteo เป็น API ที่ดีที่สุดสำหรับมือใหม่ ไม่ต้อง Key มี Historical Data และ Free ไม่จำกัด") +
        "<h3>Kaggle Datasets ยอดนิยมสำหรับ DE</h3>"
        "<p><strong>NYC Yellow Taxi Trips:</strong> 100M+ Rows หลายปี | "
        "Parquet Format | ดีสำหรับ Batch Processing + Partitioning</p>"
        "<p><strong>Stack Overflow Developer Survey:</strong> ข้อมูล Survey หลายปี | "
        "CSV | ดีสำหรับ Trend Analysis + dbt Modeling</p>"
        "<p><strong>Airbnb Listings (Inside Airbnb):</strong> หลายเมืองทั่วโลก | "
        "CSV | ดีสำหรับ Geographic Analysis + Pricing Model</p>"
        "<p><strong>Olist E-commerce Dataset:</strong> Brazilian E-commerce | "
        "Multiple CSV Tables | ดีสำหรับ Data Modeling + Star Schema</p>"
        "<p><strong>IMDb Datasets:</strong> Movies Ratings Actors | "
        "TSV | ดีสำหรับ Graph Analysis + Recommendation</p>"
        "<h3>Ingestion Patterns แยกตาม Source Type</h3>"
        "<p><strong>REST API:</strong> requests library + Pagination + Rate Limiting + Retry Logic</p>"
        "<p><strong>Streaming API (WebSocket):</strong> websocket-client + Kafka Producer</p>"
        "<p><strong>File Downloads:</strong> requests + Chunked Download + Checksum Validation</p>"
        "<p><strong>Database CDC:</strong> Debezium + Kafka Connect</p>"
        "<p><strong>Web Scraping:</strong> BeautifulSoup + Selenium + Scrapy (ตรวจ ToS ก่อน)</p>"
        "<h3>Faker Library สำหรับ Synthetic Data</h3>"
        "<pre><code>"
        "from faker import Faker\n"
        "import pandas as pd\n"
        "import random\n"
        "from datetime import datetime, timedelta\n"
        "\n"
        "fake = Faker(&apos;th_TH&apos;)  # Thai locale\n"
        "\n"
        "def generate_orders(n: int = 100000) -> pd.DataFrame:\n"
        "    orders = []\n"
        "    for _ in range(n):\n"
        "        orders.append({\n"
        "            &apos;order_id&apos;: fake.uuid4(),\n"
        "            &apos;customer_id&apos;: fake.uuid4(),\n"
        "            &apos;product_id&apos;: random.randint(1, 1000),\n"
        "            &apos;amount&apos;: round(random.uniform(10, 5000), 2),\n"
        "            &apos;status&apos;: random.choice([&apos;pending&apos;, &apos;completed&apos;, &apos;cancelled&apos;]),\n"
        "            &apos;created_at&apos;: fake.date_time_between(\n"
        "                start_date=&apos;-2y&apos;, end_date=&apos;now&apos;\n"
        "            ).isoformat()\n"
        "        })\n"
        "    return pd.DataFrame(orders)\n"
        "</code></pre>"
        "<h3>ข้อมูล Open Data ไทย (data.go.th)</h3>"
        "<p>data.go.th มีข้อมูลจากภาครัฐไทยหลายพันชุด หมวดที่น่าสนใจ:</p>"
        "<p>สุขภาพ: ข้อมูลโรงพยาบาล, สถิติผู้ป่วย | "
        "เศรษฐกิจ: ราคาสินค้า, GDP จังหวัด | "
        "การศึกษา: ผลการเรียน, จำนวนนักเรียน | "
        "สิ่งแวดล้อม: คุณภาพอากาศ PM2.5, น้ำ | "
        "การเกษตร: ราคาพืชผล, สภาพดินฟ้าอากาศ</p>"
        "<h3>Data Licensing Types ที่ต้องรู้</h3>"
        "<p><strong>Creative Commons CC0:</strong> Public Domain ใช้ได้ทุกอย่าง</p>"
        "<p><strong>CC BY:</strong> ต้อง Credit เจ้าของ</p>"
        "<p><strong>CC BY-SA:</strong> ต้อง Credit + Share-alike</p>"
        "<p><strong>MIT License:</strong> ใช้ได้อิสระ ต้องใส่ Copyright</p>"
        "<p><strong>Apache 2.0:</strong> ใช้ได้อิสระ ต้องระบุการเปลี่ยนแปลง</p>"
        + tip("ตรวจ License ของ Dataset ก่อนเสมอ บาง Dataset ห้ามใช้ Commercial จะเป็นปัญหาถ้าทำงานในบริษัท")
    )


def ch6_presentation() -> str:
    return (
        "<h2>Interview Preparation: นำเสนอ Portfolio ให้โดดเด่น</h2>"
        "<p>การมี Portfolio ที่ดีเป็นแค่ครึ่งทาง อีกครึ่งคือการนำเสนอและตอบคำถามได้ดี "
        "บทนี้จะเตรียมคุณให้พร้อมสำหรับทุกขั้นตอนของ Interview Process "
        "รวมถึง Technical Questions, System Design, และ Salary Negotiation</p>"
        "<h3>20 Technical Questions พร้อม Model Answers</h3>"
        "<p><strong>Q1: อธิบายความแตกต่างระหว่าง ETL กับ ELT</strong></p>"
        "<p>A: ETL (Extract-Transform-Load) Transform ข้อมูลก่อน Load เข้า DW "
        "ใช้ใน Legacy Systems ที่ DW มี Storage จำกัด "
        "ELT (Extract-Load-Transform) Load Raw Data เข้าก่อนแล้วค่อย Transform "
        "เหมาะกับ Modern Cloud DW เช่น BigQuery ที่ Storage ถูกและ Compute แยกกัน "
        "dbt ใช้ ELT Pattern โดยรัน SQL Transformation ใน DW โดยตรง</p>"
        "<p><strong>Q2: อธิบาย Slowly Changing Dimension (SCD) Type 1, 2, 3</strong></p>"
        "<p>A: SCD Type 1: Overwrite ค่าเก่าด้วยค่าใหม่ ไม่เก็บประวัติ "
        "SCD Type 2: เพิ่ม Row ใหม่พร้อม Valid_From/Valid_To และ Is_Current Flag "
        "ใช้บ่อยที่สุดเพราะเก็บประวัติทั้งหมด "
        "SCD Type 3: เพิ่ม Column ใหม่เก็บค่าก่อนหน้า เหมาะถ้าต้องการแค่ก่อนหน้า 1 Version</p>"
        "<p><strong>Q3: อธิบาย Idempotency ใน Data Pipeline</strong></p>"
        "<p>A: Idempotency คือคุณสมบัติที่รัน Pipeline ซ้ำหลายครั้งให้ผลลัพธ์เดิม "
        "สำคัญมากเพราะ Pipeline อาจ Fail แล้วต้อง Retry "
        "ทำได้โดยใช้ MERGE แทน INSERT, ลบข้อมูล Partition ก่อนแล้ว Insert ใหม่ "
        "หรือใช้ Watermark เพื่อ Track ว่า Process ถึงไหนแล้ว</p>"
        "<p><strong>Q4: Data Lake vs Data Warehouse vs Data Lakehouse คืออะไร</strong></p>"
        "<p>A: Data Lake เก็บ Raw Data ทุก Format (structured, semi-structured, unstructured) "
        "ราคาถูกแต่ Query ยาก "
        "Data Warehouse เก็บ Structured, Processed Data ราคาแพงกว่าแต่ Query เร็ว "
        "Data Lakehouse รวมข้อดีทั้งสอง เก็บ Raw + Processed ใน Object Storage "
        "ใช้ Table Format เช่น Delta Lake หรือ Apache Iceberg ให้ Query ได้เหมือน DW</p>"
        "<p><strong>Q5: ถ้า Pipeline ล้มเหลวกลางคัน จะแก้อย่างไร</strong></p>"
        "<p>A: 1) ดู Airflow UI หา Task ที่ Fail และดู Logs "
        "2) Check Error Message ว่าเป็น Transient Error (Network, Timeout) หรือ Logical Error (Schema Change) "
        "3) ถ้า Transient: Retry Task ด้วย Clear Task ใน Airflow "
        "4) ถ้า Data Issue: Fix Source Data และ Re-run "
        "5) ตรวจสอบ Downstream Tasks ว่า Data สอดคล้องกันหรือไม่ "
        "6) Alert Team และ Document Incident</p>"
        + tip("เตรียม 2-3 ตัวอย่าง Incidents จริงจาก Project ของคุณที่แก้ได้สำเร็จเพื่อใช้ใน Interview") +
        "<p><strong>Q6: อธิบาย Medallion Architecture</strong></p>"
        "<p>A: Bronze Layer เก็บ Raw Data ทุกอย่างจาก Source ไม่แตะต้อง เก็บเป็น Append-only "
        "Silver Layer ทำ Cleansing Validation และ Standardization แต่ยังเป็น Atomic Data "
        "Gold Layer Business-ready Tables สำหรับ Analytics เช่น Fact และ Dimension Tables "
        "ข้อดีคือ Reprocessing ทำได้เสมอเพราะเก็บ Raw ไว้</p>"
        "<p><strong>Q7: Partition vs Clustering ใน BigQuery</strong></p>"
        "<p>A: Partition แบ่ง Table เป็น Segment ตาม Column (มักเป็น Date) "
        "Query ที่ Filter ด้วย Partition Column จะ Scan แค่ Partition ที่ระบุ ประหยัด Cost "
        "Clustering จัด Sort ข้อมูลใน Partition ตาม Column ที่ระบุ "
        "เหมาะสำหรับ High Cardinality Columns เช่น Customer_ID "
        "ใช้ทั้งสองร่วมกัน: Partition by Date + Cluster by Customer_ID</p>"
        "<p><strong>Q8: อธิบาย dbt Tests ที่ใช้บ่อย</strong></p>"
        "<p>A: not_null ตรวจ NULL, unique ตรวจ Duplicate, "
        "accepted_values ตรวจค่าที่ถูกต้อง, relationships ตรวจ Referential Integrity "
        "Custom Tests เช่น row_count_growth_threshold, "
        "freshness check ว่าข้อมูลใหม่พอหรือไม่</p>"
        "<p><strong>Q9: ถ้า Data Volume เพิ่มขึ้น 100 เท่า จะ Scale อย่างไร</strong></p>"
        "<p>A: Batch: แบ่ง Process เป็น Micro-batches ใช้ Spark แทน Pandas "
        "เพิ่ม Partitioning และ Parallelism ย้ายไป Cloud-native Service "
        "Streaming: เพิ่ม Kafka Partition เพิ่ม Consumer/Worker "
        "Storage: ใช้ Columnar Format (Parquet) แทน CSV เพิ่ม Compression</p>"
        "<h3>STAR Method สำหรับ Project Stories</h3>"
        "<p><strong>Situation:</strong> บริบทของ Project เช่น บริษัทมีปัญหาข้อมูล Order ไม่ถูกต้อง</p>"
        "<p><strong>Task:</strong> สิ่งที่คุณต้องทำ เช่น สร้าง Data Quality Pipeline</p>"
        "<p><strong>Action:</strong> สิ่งที่คุณทำจริง เช่น ใช้ Great Expectations + Airflow</p>"
        "<p><strong>Result:</strong> ผลลัพธ์ที่วัดได้ เช่น ลด Data Errors 95%, ประหยัดเวลา 10 ชั่วโมง/สัปดาห์</p>"
        "<h3>Virtual Interview Checklist</h3>"
        "<p>✅ ทดสอบ Camera + Microphone 30 นาทีก่อน Interview</p>"
        "<p>✅ Lighting สว่างเพียงพอ ไม่มีแสงด้านหลัง</p>"
        "<p>✅ Background สะอาดหรือใช้ Virtual Background</p>"
        "<p>✅ เปิด Code Editor และ Browser Tab ที่ใช้ Demo ไว้ล่วงหน้า</p>"
        "<p>✅ มี GitHub และ Dashboard Link พร้อม Paste</p>"
        "<p>✅ ปิด Notification ทุกอย่าง</p>"
        "<p>✅ มี Backup Plan ถ้า Internet ขัดข้อง (Mobile Hotspot)</p>"
        "<h3>Salary Negotiation Framework</h3>"
        "<p><strong>ขั้นตอน 1 - Research:</strong> ดู Glassdoor, LinkedIn Salary, Levels.fyi "
        "หาเงินเดือน Market Rate สำหรับ DE ระดับเดียวกันในบริษัทขนาดเดียวกัน</p>"
        "<p><strong>ขั้นตอน 2 - Anchor High:</strong> เสนอเลขที่สูงกว่า Target 15-20% "
        "เพื่อให้มีพื้นที่ Negotiate</p>"
        "<p><strong>ขั้นตอน 3 - Justify:</strong> ใช้ Portfolio Projects และ Skills ที่หายากเป็น Leverage</p>"
        "<p><strong>ขั้นตอน 4 - Consider Total Comp:</strong> Base + Bonus + Stock + Benefits</p>"
        "<h3>Offer Evaluation Matrix</h3>"
        "<p>เงินเดือน (น้ำหนัก 30%) | Tech Stack ที่ได้เรียนรู้ (20%) | "
        "Growth Opportunity (20%) | Work-life Balance (15%) | "
        "Team/Manager Quality (15%)</p>"
    )


def ch7_resume() -> str:
    return (
        "<h2>Resume/CV Format สำหรับ Data Engineer: ATS-Optimized Guide</h2>"
        "<p>Resume ที่ดีต้องผ่านทั้ง ATS Software และ Human Recruiter "
        "ซึ่งมักใช้เวลาเฉลี่ยแค่ 7-15 วินาทีใน First Scan "
        "บทนี้จะครอบคลุม ATS Optimization, Resume Templates สำหรับทุกระดับ "
        "และ Checklist ครบถ้วน 50 ข้อ</p>"
        "<h3>ATS Optimization Guide</h3>"
        "<p>ATS (Applicant Tracking System) เช่น Workday, Greenhouse, Lever "
        "จะ Parse Resume และให้ Score ตาม Keywords ที่ตรงกับ JD "
        "Rules พื้นฐาน:</p>"
        "<p>1. ใช้ Standard Section Headers: Work Experience, Education, Skills "
        "(ไม่ใช้ชื่อแปลกเช่น My Journey หรือ Where I Worked)</p>"
        "<p>2. ใช้ Standard Fonts: Arial, Calibri, Times New Roman ขนาด 10-12pt</p>"
        "<p>3. ไม่ใส่ข้อมูลใน Table, Text Box, หรือ Header/Footer เพราะ ATS อ่านไม่ได้</p>"
        "<p>4. Save เป็น .docx หรือ .pdf ขึ้นกับบริษัท (ถามก่อนถ้าไม่แน่ใจ)</p>"
        "<p>5. Tailor Keywords จาก JD แต่ละงานให้ตรงกับ Resume</p>"
        + tip("ใช้ Jobscan.co หรือ ResyMatch เพื่อ Analyze ว่า Resume ตรงกับ JD แค่ไหน") +
        "<h3>Resume Template: Entry Level (0-2 ปี)</h3>"
        "<p>ส่วนบน: ชื่อ | Email | Phone | LinkedIn | GitHub</p>"
        "<p>Summary: Data Engineering graduate with hands-on experience building "
        "ETL pipelines using Python and Apache Airflow. "
        "Demonstrated ability to design scalable data models with dbt and BigQuery "
        "through portfolio projects processing 1M+ records.</p>"
        "<p>Technical Skills: "
        "Languages: Python (Pandas, PySpark), SQL | "
        "Orchestration: Apache Airflow | "
        "Transformation: dbt | "
        "Cloud: GCP (BigQuery, GCS), AWS basics | "
        "Containers: Docker | "
        "Version Control: Git, GitHub Actions</p>"
        "<p>Projects (แทน Work Experience): "
        "E-commerce Data Platform | GitHub Link | "
        "Built end-to-end pipeline processing 500K daily orders using Airflow + dbt + BigQuery | "
        "Reduced data freshness from 24 hours to 1 hour | "
        "Implemented 40+ dbt tests achieving 99.5% data quality score</p>"
        "<h3>Resume Template: Mid Level (2-5 ปี)</h3>"
        "<p>เพิ่ม: Work Experience Section ก่อน Projects | "
        "ใส่ Quantified Achievements | "
        "เพิ่ม System Design Contributions | "
        "ใส่ Streaming Technologies (Kafka, Flink)</p>"
        "<h3>Resume Template: Senior Level (5+ ปี)</h3>"
        "<p>เพิ่ม: Leadership Experience | "
        "Cross-functional Impact | "
        "Platform/Infrastructure Ownership | "
        "Mentoring | "
        "Architecture Design Decisions | "
        "Business Impact ในเชิง Revenue หรือ Cost</p>"
        "<h3>Quantification Formula</h3>"
        "<p>ทุก Bullet Point ควรตอบ: ทำอะไร + โดยใช้อะไร + ผลลัพธ์เป็น % หรือตัวเลข</p>"
        "<p>แย่: Built data pipeline for orders</p>"
        "<p>ดี: Designed Airflow pipeline processing 2M daily orders, "
        "reducing latency from 4h to 15min and saving $12K/month in compute costs</p>"
        "<p>แย่: Improved query performance</p>"
        "<p>ดี: Optimized BigQuery queries using partitioning and clustering, "
        "reducing scan costs by 78% ($3,200/month savings)</p>"
        "<h3>Action Verbs สำหรับ DE Resume (20+ คำ)</h3>"
        "<p>Architected | Designed | Built | Developed | Engineered | Implemented | "
        "Optimized | Automated | Orchestrated | Migrated | Reduced | Improved | "
        "Scaled | Deployed | Monitored | Maintained | Collaborated | Led | Mentored | "
        "Integrated | Transformed | Modeled | Validated | Streamlined</p>"
        "<h3>Skills Taxonomy สำหรับ DE</h3>"
        "<p><strong>Core Programming:</strong> Python, SQL, Scala, Java, Bash</p>"
        "<p><strong>Orchestration:</strong> Apache Airflow, Prefect, Dagster, Luigi</p>"
        "<p><strong>Batch Processing:</strong> Apache Spark, PySpark, Hadoop MapReduce</p>"
        "<p><strong>Stream Processing:</strong> Apache Kafka, Apache Flink, AWS Kinesis</p>"
        "<p><strong>Data Warehouse:</strong> BigQuery, Snowflake, Redshift, Databricks</p>"
        "<p><strong>Data Lake:</strong> AWS S3, GCS, Azure Data Lake, Delta Lake, Iceberg</p>"
        "<p><strong>Transformation:</strong> dbt, Apache Spark SQL, Pandas</p>"
        "<p><strong>Data Quality:</strong> Great Expectations, dbt tests, Monte Carlo</p>"
        "<p><strong>IaC:</strong> Terraform, Pulumi, CloudFormation</p>"
        "<p><strong>Containers:</strong> Docker, Kubernetes, Helm</p>"
        "<p><strong>CI/CD:</strong> GitHub Actions, GitLab CI, Jenkins</p>"
        "<h3>Thai vs International Format Differences</h3>"
        "<p><strong>ไทย:</strong> รูปถ่าย | วันเกิด | สัญชาติ | 1-2 หน้า | "
        "ภาษาไทยในส่วน Experience | เงินเดือนที่ต้องการ</p>"
        "<p><strong>International:</strong> ไม่มีรูป | ไม่บอก DOB | ไม่บอก Nationality | "
        "1 หน้า (Junior), 2 หน้า (Senior) | ภาษาอังกฤษตลอด | ไม่ระบุเงินเดือน</p>"
        "<h3>50-Item Resume Review Checklist</h3>"
        "<p>Contact: ✅ Email Professional ✅ GitHub Link ✅ LinkedIn URL ✅ Portfolio Site</p>"
        "<p>Format: ✅ ไม่มี Photo (International) ✅ Font มาตรฐาน ✅ Margin 0.5-1 inch ✅ Bullet Points</p>"
        "<p>Content: ✅ Summary ตรงกับ JD ✅ Keywords ครบ ✅ Quantified Achievements ✅ Action Verbs</p>"
        "<p>Skills: ✅ จัดกลุ่ม Skills ✅ ไม่ใส่ Microsoft Office ✅ ระบุ Level (Proficient/Familiar)</p>"
        "<p>Projects: ✅ GitHub Link ✅ Tech Stack ชัดเจน ✅ Impact วัดได้ ✅ ไม่ใช่ Tutorial Clone</p>"
    )


def ch8_linkedin() -> str:
    return (
        "<h2>LinkedIn Profile Optimization สำหรับ Data Engineer</h2>"
        "<p>LinkedIn คือแหล่ง Recruit อันดับหนึ่งในวงการ Tech "
        "มากกว่า 90% ของ Recruiters ใช้ LinkedIn ในการหาผู้สมัคร "
        "Profile ที่ Optimized จะทำให้ Recruiter หาเจอและ Reach Out มาหาคุณโดยไม่ต้องสมัครเอง "
        "บทนี้จะครอบคลุมทุก Aspect ของ LinkedIn Optimization</p>"
        "<h3>LinkedIn SSI (Social Selling Index) Score</h3>"
        "<p>LinkedIn ให้ Score 0-100 ที่แบ่งเป็น 4 Pillars:</p>"
        "<p><strong>1. Establish Professional Brand (25 pts):</strong> "
        "Profile Completeness, Profile Photo, Headline, Summary, Skills Endorsements | "
        "ทำให้สูง: Complete ทุก Section ให้ได้ All-Star Status</p>"
        "<p><strong>2. Find the Right People (25 pts):</strong> "
        "ใช้ Advanced Search, ดู Profiles ที่ Relevant | "
        "ทำให้สูง: Search และ Visit Profiles DE/Recruiters ทุกวัน</p>"
        "<p><strong>3. Engage with Insights (25 pts):</strong> "
        "Like Comment Share Content | "
        "ทำให้สูง: Engage กับ Content ใน Feed ทุกวัน 10-15 นาที</p>"
        "<p><strong>4. Build Relationships (25 pts):</strong> "
        "Connect กับคนใหม่, Message First-degree Connections | "
        "ทำให้สูง: ส่ง Personalized Connection Requests 5-10 คน/สัปดาห์</p>"
        + tip("SSI Score 60+ จะ Boost Profile ใน Search Algorithm และทำให้ Recruiter หาเจอง่ายขึ้น") +
        "<h3>Headline Formula + 5 Examples</h3>"
        "<p>Formula: [Role] | [Tools] | [Value Proposition]</p>"
        "<p>Example 1: Data Engineer | Python • Airflow • dbt • BigQuery | Building Scalable Pipelines at Scale</p>"
        "<p>Example 2: Senior Data Engineer | Spark • Kafka • Snowflake | Turning Data Chaos into Business Insights</p>"
        "<p>Example 3: Data Engineer (Open to Work) | dbt • Airflow • BigQuery | Ex-SCB Tech | 5 Years Fintech Data</p>"
        "<p>Example 4: Data Engineering Lead | GCP • Databricks • dbt | Architecting Data Platforms for Growth</p>"
        "<p>Example 5: Junior Data Engineer | Python • SQL • Airflow | Computer Science Graduate | Portfolio: github.com/name</p>"
        "<h3>About Section Template</h3>"
        "<p>ย่อหน้า 1 (Hook): เริ่มด้วยประโยคที่ดึงดูดความสนใจ "
        "เช่น I help companies make faster decisions by building data pipelines that actually work.</p>"
        "<p>ย่อหน้า 2 (Background): อธิบาย Background และ Journey สู่ DE</p>"
        "<p>ย่อหน้า 3 (Expertise): ระบุ Area of Expertise ที่ชัดเจน</p>"
        "<p>ย่อหน้า 4 (Outside Work): สิ่งที่สนใจนอกจากงาน เพื่อ Human Connection</p>"
        "<p>ย่อหน้า 5 (CTA): Call to Action เช่น Feel free to connect หรือ Open to DE opportunities</p>"
        "<h3>LinkedIn SEO Keywords สำหรับ DE</h3>"
        "<p>ใส่ Keywords เหล่านี้ใน Headline, About, Experience, Skills:</p>"
        "<p>Data Engineer | Data Engineering | ETL | ELT | Data Pipeline | "
        "Apache Airflow | Apache Spark | dbt | BigQuery | Snowflake | "
        "Apache Kafka | Data Warehouse | Data Lake | Data Lakehouse | "
        "Python | SQL | PySpark | Data Modeling | Data Architecture | "
        "Delta Lake | Apache Iceberg | Real-time Analytics | Batch Processing</p>"
        "<h3>Content Strategy Table</h3>"
        "<p><strong>สิ่งที่ควรโพสต์:</strong></p>"
        "<p>TIL (Today I Learned): สิ่งที่เรียนรู้ใหม่ | ทุกวัน | Short Post + Code Snippet</p>"
        "<p>Project Update: Progress บน Portfolio Project | สัปดาห์ละ 1 ครั้ง | Post + Screenshot</p>"
        "<p>Article: Deep Dive บน Technical Topic | เดือนละ 1-2 ครั้ง | Long-form Article</p>"
        "<p>Engage: Comment บน Posts ของ Thought Leaders | ทุกวัน | Thoughtful 3-5 ประโยค</p>"
        "<p>Share: บทความที่น่าสนใจ + Commentary | สัปดาห์ละ 2-3 ครั้ง | Add Insight</p>"
        "<h3>LinkedIn Algorithm Factors</h3>"
        "<p>ปัจจัยที่ส่งผลต่อ Reach ของ Post: "
        "Early Engagement (Comments ใน 1 ชั่วโมงแรก) | "
        "Dwell Time (คนอ่านนานแค่ไหน) | "
        "Relevance (Topic ตรงกับ Audience ไหม) | "
        "Native Content (Video/Document ดีกว่า External Link) | "
        "Connections Strength (ผู้ Engage รู้จักคุณดีแค่ไหน)</p>"
        "<h3>Connection Request Templates</h3>"
        "<p><strong>To DE at Target Company:</strong> "
        "Hi [Name], I noticed you work as a Data Engineer at [Company]. "
        "I&apos;m currently building my DE portfolio (working with Airflow + dbt + BigQuery) "
        "and would love to connect and learn from your experience. No pressure at all!</p>"
        "<p><strong>To Recruiter:</strong> "
        "Hi [Name], I&apos;m a Data Engineer with [X] years of experience in [Tech Stack]. "
        "I&apos;m currently exploring new opportunities and would love to connect.</p>"
        "<p><strong>To Conference Speaker:</strong> "
        "Hi [Name], I really enjoyed your talk on [Topic] at [Conference]. "
        "Your point about [Specific Thing] changed how I think about [Topic]. Would love to connect!</p>"
        "<h3>Creator Mode Benefits</h3>"
        "<p>เปิด Creator Mode เพื่อ: Follow Button แทน Connect (Build Audience), "
        "แสดง Topics ที่คุณ Create Content (Algorithm Boost), "
        "Featured Section โดดเด่นขึ้น, "
        "LinkedIn Live Access, "
        "Newsletter Feature</p>"
    )


def ch9_mistakes() -> str:
    return (
        "<h2>15 Portfolio Mistakes ที่ทำให้ไม่ได้งาน Data Engineer</h2>"
        "<p>การหลีกเลี่ยงข้อผิดพลาดเหล่านี้สำคัญเท่ากับการทำสิ่งถูกต้อง "
        "ข้อผิดพลาดหนึ่งอย่างอาจทำให้ Interviewer ติดใจและไม่ Call Back "
        "บทนี้รวบรวม 15 ข้อผิดพลาดที่พบบ่อยพร้อม Before-After Examples "
        "และ 40-Item Portfolio Review Checklist</p>"
        "<h3>15 Portfolio Mistakes Table</h3>"
        "<p><strong>Mistake 1: ทำตาม Tutorial 100% โดยไม่เปลี่ยนแปลงอะไร</strong></p>"
        "<p>Example: Clone ตาม YouTube Tutorial Airflow + BigQuery โดยใช้ Data Source เดิม "
        "Interviewer เห็น 20 คนที่ทำ Project เดียวกัน</p>"
        "<p>Fix: เปลี่ยน Data Source เป็นอย่างอื่น เพิ่ม Feature ใหม่ "
        "เปลี่ยน Tech Stack บางส่วน และ Write Own Documentation</p>"
        "<p><strong>Mistake 2: ไม่มี README หรือ README ว่างๆ</strong></p>"
        "<p>Example: Repository มีแค่ Code Files ไม่มี README.md "
        "Interviewer Clone แล้วไม่รู้จะ Run อย่างไร</p>"
        "<p>Fix: README ต้องมี Overview, Architecture Diagram, Quick Start, "
        "Configuration, และ Known Issues</p>"
        "<p><strong>Mistake 3: Hardcode Credentials ใน Code</strong></p>"
        "<p>Example: api_key = &apos;AIzaSyAbc123...&apos; ใน Python File ที่ Commit ไป GitHub</p>"
        "<p>Fix: ใช้ os.environ.get(&apos;API_KEY&apos;) + .env file + .gitignore "
        "ถ้า Commit ไปแล้วให้ Revoke Key ทันทีและใช้ git-secrets ป้องกัน</p>"
        + tip("ติดตั้ง pre-commit hooks ด้วย detect-secrets เพื่อตรวจ Credentials ก่อน Commit อัตโนมัติ") +
        "<p><strong>Mistake 4: Project รันไม่ได้บน Fresh Machine</strong></p>"
        "<p>Example: requirements.txt ไม่มี Version Fixed, "
        "มี Hardcode Path เช่น /Users/myname/data/ "
        "ไม่มี Environment Setup Guide</p>"
        "<p>Fix: ใช้ Docker Compose ให้ครบ, Pin Dependency Versions, "
        "ใช้ Relative Paths หรือ Environment Variables, "
        "ทดสอบ Clone และ Run บน Machine ใหม่ก่อน Push</p>"
        "<p><strong>Mistake 5: ทำหลาย Project ไม่สมบูรณ์สักอัน</strong></p>"
        "<p>Example: มี 15 Repository แต่ทุกอันมี Commit แค่ 2-3 ครั้ง "
        "README เป็น Template Default, ไม่มี Tests</p>"
        "<p>Fix: Focus ที่ 2-3 Projects และทำให้สมบูรณ์ก่อน "
        "Archive หรือ Delete Repos ที่ไม่ได้ใช้</p>"
        "<p><strong>Mistake 6: ไม่มี Tests</strong></p>"
        "<p>Example: Code 2,000 บรรทัดแต่ไม่มีไฟล์ test_*.py เลย</p>"
        "<p>Fix: เขียน Unit Tests สำหรับ Transformation Functions "
        "เพิ่ม dbt Tests (not_null, unique, accepted_values) "
        "ตั้ง Coverage Target 70%+</p>"
        "<p><strong>Mistake 7: ใช้ Pandas สำหรับ Large Dataset</strong></p>"
        "<p>Example: อ่าน NYC Taxi CSV 50GB เข้า pd.read_csv() แล้ว RAM หมด</p>"
        "<p>Fix: ใช้ PySpark หรือ DuckDB สำหรับ Large Dataset, "
        "ใช้ Chunked Reading ถ้าต้องใช้ Pandas "
        "และ Explain ใน README ว่าเลือก Tool นี้เพราะอะไร</p>"
        "<p><strong>Mistake 8: Architecture Diagram ซับซ้อนเกินจริง</strong></p>"
        "<p>Example: Diagram มี 30+ Components แต่ Project จริงมีแค่ Python Script + BigQuery</p>"
        "<p>Fix: Diagram ต้อง Reflect ความจริง อธิบาย Design Decisions ที่ทำจริง "
        "ไม่ใช่ Aspirational Architecture</p>"
        "<p><strong>Mistake 9: ไม่ตอบ Why บน Design Decisions</strong></p>"
        "<p>Example: ถาม ทำไมเลือก Airflow แทน Prefect คำตอบ เพราะเห็นใน Tutorial</p>"
        "<p>Fix: เขียน ADR บันทึก Rationale เช่น เลือก Airflow เพราะ Mature Ecosystem, "
        "หลาย Production References, และ Strong Community Support</p>"
        "<p><strong>Mistake 10: Project ที่ Business ไม่สนใจ</strong></p>"
        "<p>Example: Pipeline ที่ Predict ว่า Pokemon แบบไหน Rare ที่สุด</p>"
        "<p>Fix: เลือก Domain ที่ Business ใช้จริง เช่น Finance, Retail, Healthcare, "
        "Logistics และ Frame ใน Terms ของ Business Value</p>"
        "<p><strong>Mistake 11: ไม่มี CI/CD</strong></p>"
        "<p>Example: ไม่มีไฟล์ .github/workflows/ เลย</p>"
        "<p>Fix: เพิ่ม GitHub Actions Workflow อย่างน้อย Run Lint + Tests "
        "ทำให้ Badge Build Passing สีเขียวปรากฏใน README</p>"
        "<p><strong>Mistake 12: Schema ไม่มี Documentation</strong></p>"
        "<p>Example: BigQuery Table ชื่อ tbl1, col1, col2, col3 ไม่มีคำอธิบาย</p>"
        "<p>Fix: ตั้งชื่อ Table และ Column ให้สื่อความหมาย "
        "เพิ่ม Description ใน dbt Schema.yml "
        "สร้าง Data Dictionary Document</p>"
        "<p><strong>Mistake 13: Public Commit History ที่ไม่สะอาด</strong></p>"
        "<p>Example: Commit Messages เช่น fix, test123, asdfgh, final_FINAL_v2</p>"
        "<p>Fix: ใช้ Conventional Commits, ทำ Interactive Rebase เพื่อ Clean History "
        "ก่อน Pin เป็น Portfolio Project</p>"
        "<p><strong>Mistake 14: ไม่ Monitor Data Quality</strong></p>"
        "<p>Example: Pipeline รันได้แต่ไม่รู้ว่า Data ถูกต้องไหม</p>"
        "<p>Fix: เพิ่ม Data Quality Checks ด้วย dbt Tests หรือ Great Expectations "
        "แสดง Quality Score ใน Dashboard</p>"
        "<p><strong>Mistake 15: GitHub Profile ดูไม่เป็นมืออาชีพ</strong></p>"
        "<p>Example: Profile Photo ไม่มี, Bio ว่าง, ไม่มี Profile README, "
        "ชื่อ Username เป็น xXxDarkLord2005xXx</p>"
        "<p>Fix: ใส่ Professional Photo, เขียน Bio สั้นๆ, "
        "สร้าง Profile README, เปลี่ยน Username เป็นชื่อจริง</p>"
        "<h3>40-Item Portfolio Review Checklist</h3>"
        "<p><strong>GitHub Profile (10 items):</strong></p>"
        "<p>✅ Professional Photo ✅ Bio บอก Role และ Tech Stack "
        "✅ Profile README มี GitHub Stats ✅ 4-6 Pinned Repos "
        "✅ Contribution Graph สม่ำเสมอ ✅ ไม่มี Empty Repos "
        "✅ Username เป็นชื่อจริง ✅ Location และ Website ครบ "
        "✅ Pinned Repos มี Description ✅ Topics/Tags ครบ</p>"
        "<p><strong>Per Project (20 items):</strong></p>"
        "<p>✅ README สมบูรณ์ ✅ Architecture Diagram ✅ Quick Start ใช้ได้จริง "
        "✅ Docker Compose หรือ Setup Script ✅ .env.example ✅ .gitignore ถูกต้อง "
        "✅ ไม่มี Credentials ใน Code ✅ Unit Tests ✅ CI/CD Pipeline "
        "✅ Meaningful Commit Messages ✅ Conventional Commits "
        "✅ Project รันได้บน Fresh Machine ✅ Makefile Tasks "
        "✅ Requirements.txt Version Fixed ✅ License File "
        "✅ Changelog หรือ Release Notes ✅ ADR Documents "
        "✅ Data Dictionary ✅ Monitoring Setup ✅ บันทึก Known Issues</p>"
        "<p><strong>Content Quality (10 items):</strong></p>"
        "<p>✅ ไม่ใช่ Tutorial Clone 100% ✅ มี Business Value ชัดเจน "
        "✅ Tech Stack เหมาะสมกับ Scale ✅ มี Trade-off Discussion "
        "✅ Data Source น่าสนใจ ✅ Volume ใหญ่พอสมควร "
        "✅ Dashboard/Visualization ✅ Error Handling ครบ "
        "✅ Logging ที่ดี ✅ Performance Optimization</p>"
    )


# ---------------------------------------------------------------------------
# Build the full JS file
# ---------------------------------------------------------------------------

chapters_data = [
    (0, 'overview',        '🏆', 'ทำไม Portfolio สำคัญกว่า Certification',          ch0_overview()),
    (1, 'github-profile',  '👾', 'GitHub Profile: README, Pinned Repos, และ Contributions', ch1_github()),
    (2, 'project-ideas',   '💡', '10 Project Ideas ระดับ Professional สำหรับ DE Portfolio', ch2_project_ideas()),
    (3, 'end-to-end',      '🔄', 'สร้าง E2E Pipeline: จาก Source ถึง Dashboard',   ch3_end_to_end()),
    (4, 'documentation',   '📝', 'Documentation: README และ Architecture Diagram',  ch4_documentation()),
    (5, 'data-sources',    '🗄️', 'Free Data Sources: API และ Kaggle',               ch5_data_sources()),
    (6, 'presentation',    '🎤', 'นำเสนอ Portfolio ใน Interview',                   ch6_presentation()),
    (7, 'resume',          '📄', 'Resume/CV Format สำหรับ Data Engineer',            ch7_resume()),
    (8, 'linkedin',        '💼', 'LinkedIn Profile สำหรับ Data Engineer',            ch8_linkedin()),
    (9, 'common-mistakes', '⚠️', 'ข้อผิดพลาด Portfolio ที่พบบ่อย',                 ch9_mistakes()),
]

lines = ["export const chapters = ["]
for i, (num, slug, emoji, title, content) in enumerate(chapters_data):
    comma = "," if i < len(chapters_data) - 1 else ""
    lines.append(build_chapter(num, slug, emoji, title, content) + comma)
lines.append("];")
lines.append("")

output = "\n".join(lines)

# Verify size
size_kb = len(output.encode('utf-8')) / 1024
print(f"Generated content size: {size_kb:.1f} KB")

# Chapter size breakdown
import re
for i, (num, slug, emoji, title, content) in enumerate(chapters_data):
    ch_size = len(content.encode('utf-8'))
    print(f"  Chapter {num} ({slug}): {ch_size} chars ({ch_size/1024:.1f} KB)")

if size_kb < 60:
    print(f"WARNING: File is only {size_kb:.1f} KB, target is 60 KB+")
else:
    print(f"✅ Target met: {size_kb:.1f} KB >= 60 KB")

# Write output
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    f.write(output)

print(f"\n✅ Written to: {OUTPUT_PATH}")
print(f"   Final size: {os.path.getsize(OUTPUT_PATH) / 1024:.1f} KB")
