#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
expand_weather.py
Generates an expanded weather-canvas.js course file (50KB+).
All JS strings use single quotes, apostrophes escaped as \\'
"""

import os

OUT = r'd:\AI\ขาย\de-course\data\courses\weather-canvas.js'

# ── helpers ──────────────────────────────────────────────────────────────────

def q(text):
    """Wrap text in single-quoted JS string, escaping apostrophes and newlines."""
    # escape backslash first
    text = text.replace('\\', '\\\\')
    # escape single quotes (real apostrophes in Thai text)
    text = text.replace("'", "\\'")
    # replace actual newlines with literal \n
    text = text.replace('\n', '\\n')
    return "'" + text + "'"


def chapter(number, slug, emoji, title, content_lines):
    """Return one chapter object as a single long line."""
    content_str = q('\n'.join(content_lines))
    title_str = q(title)
    emoji_str = q(emoji)
    slug_str = q(slug)
    return (
        f"  {{ number: {number}, slug: {slug_str}, emoji: {emoji_str}, "
        f"title: {title_str}, content: {content_str} }}"
    )


# ── Chapter 0 ─────────────────────────────────────────────────────────────────

ch0 = [
    "<h2>🌩️ สร้างเว็บแอปพยากรณ์อากาศสุดล้ำ — ภาพรวมโปรเจคทั้งหมด!</h2>",
    "<img src='/images/lessons/weather-overview.png' alt='Weather App Overview' style='max-width:100%;border-radius:12px;margin:20px 0'/>",
    "<p>ยินดีต้อนรับสู่คอร์ส <strong>Vibrant Weather App</strong> — เราจะสร้างเว็บแอปพยากรณ์อากาศที่สวยงาม ทันสมัย พร้อมแอนิเมชันเปลี่ยนตามสภาพอากาศจริงแบบเรียลไทม์! ทั้งหมดนี้ใช้เพียง <strong>HTML5, CSS3 และ Vanilla JavaScript ไฟล์เดียว</strong> — ไม่มี Framework ซับซ้อน ไม่ต้องติดตั้งอะไรเลย!</p>",
    "",
    "<div class='tip-box'><strong>💡</strong> ไม่ต้องติดตั้งอะไรเลย! — ไม่ใช้ React, Vue, Angular หรือ Library ใดๆ ทั้งสิ้น ทำงานบน Browser ได้ทุกเครื่องในโลก!</div>",
    "",
    "<h3>🎯 Learning Objectives — สิ่งที่จะได้เรียนรู้</h3>",
    "<table>",
    "  <tr><th>#</th><th>หัวข้อ</th><th>เทคนิคหลัก</th><th>ระดับ</th></tr>",
    "  <tr><td>1</td><td>ดึงข้อมูลสภาพอากาศจริง</td><td>Fetch API + Open-Meteo (ฟรี 100%)</td><td>⭐⭐</td></tr>",
    "  <tr><td>2</td><td>UI สวยแบบ Glassmorphism</td><td>CSS backdrop-filter, rgba, blur, gradient</td><td>⭐⭐</td></tr>",
    "  <tr><td>3</td><td>แอนิเมชัน Canvas 60FPS</td><td>requestAnimationFrame, context2d API</td><td>⭐⭐⭐</td></tr>",
    "  <tr><td>4</td><td>Particle System OOP</td><td>ES6 Class, ฝน เมฆ แดด หิมะ ฟ้าแลบ</td><td>⭐⭐⭐</td></tr>",
    "  <tr><td>5</td><td>Responsive + Mobile-First</td><td>CSS Grid, Flexbox, scroll-snap, Geolocation</td><td>⭐⭐</td></tr>",
    "  <tr><td>6</td><td>localStorage Cache</td><td>บันทึกข้อมูล ลดการเรียก API ซ้ำ</td><td>⭐⭐</td></tr>",
    "  <tr><td>7</td><td>พยากรณ์ 7 วัน</td><td>WMO Code → Emoji + ภาษาไทย</td><td>⭐</td></tr>",
    "  <tr><td>8</td><td>Deploy ออนไลน์</td><td>GitHub Pages + Vercel (ฟรี)</td><td>⭐</td></tr>",
    "</table>",
    "",
    "<h3>📋 Prerequisites — สิ่งที่ควรรู้ก่อน</h3>",
    "<ul>",
    "  <li>✅ HTML พื้นฐาน (div, input, table, script)</li>",
    "  <li>✅ CSS พื้นฐาน (selector, color, font, flexbox)</li>",
    "  <li>✅ JavaScript พื้นฐาน (variable, function, if/else, for loop)</li>",
    "  <li>❓ async/await — ไม่รู้ก็ไม่เป็นไร เราจะสอนตั้งแต่เริ่ม!</li>",
    "  <li>❓ OOP / Class — ไม่รู้ก็ไม่เป็นไร เราจะสอนในบทที่ 4!</li>",
    "</ul>",
    "",
    "<h3>🏗️ โครงสร้างไฟล์โปรเจค</h3>",
    "<pre><code>📁 weather-app/",
    "└── index.html          ← ไฟล์เดียวจบ! (HTML + CSS + JS รวมกัน)",
    "",
    "หรือถ้าอยากแยกไฟล์สะอาด:",
    "📁 weather-app/",
    "├── index.html          ← โครงสร้างหน้าเว็บ",
    "├── style.css           ← CSS ทั้งหมด",
    "└── app.js              ← JavaScript ทั้งหมด</code></pre>",
    "",
    "<h3>🌐 Tech Stack — เทคโนโลยีที่ใช้</h3>",
    "<table>",
    "  <tr><th>เทคโนโลยี</th><th>หน้าที่</th><th>ทำไมถึงเลือก</th></tr>",
    "  <tr><td>HTML5 Canvas</td><td>วาดแอนิเมชันพื้นหลัง</td><td>เร็ว ลื่น ควบคุมได้ทุก pixel</td></tr>",
    "  <tr><td>CSS3 Glassmorphism</td><td>UI ใสๆ สวยงาม</td><td>ทันสมัย ทำได้ด้วย CSS ล้วน</td></tr>",
    "  <tr><td>Open-Meteo API</td><td>ข้อมูลอากาศจริง</td><td>ฟรี 100% ไม่ต้องสมัคร ไม่ต้อง Key</td></tr>",
    "  <tr><td>Fetch API</td><td>ดึงข้อมูลจาก API</td><td>Built-in browser ไม่ต้อง install</td></tr>",
    "  <tr><td>localStorage</td><td>Cache ข้อมูล + Settings</td><td>เร็ว ใช้ offline ได้บางส่วน</td></tr>",
    "  <tr><td>Geolocation API</td><td>ระบุตำแหน่งผู้ใช้</td><td>Built-in browser รองรับทุก device</td></tr>",
    "</table>",
    "",
    "<h3>🏛️ Architecture Diagram — โครงสร้างการทำงาน</h3>",
    "<pre><code>┌─────────────────────────────────────────────────────┐",
    "│                   Browser (index.html)              │",
    "│                                                     │",
    "│  ┌──────────────┐     ┌────────────────────────┐   │",
    "│  │  HTML Layer   │     │     JavaScript Layer    │   │",
    "│  │  - canvas     │     │  - fetchWeather()       │   │",
    "│  │  - card UI    │◄────│  - animate()            │   │",
    "│  │  - select     │     │  - ParticleSystem       │   │",
    "│  └──────────────┘     └──────────┬─────────────┘   │",
    "│                                  │                  │",
    "│  ┌──────────────┐                │                  │",
    "│  │   CSS Layer   │     ┌──────────▼─────────────┐  │",
    "│  │ - glassmorphs │     │  Open-Meteo API         │  │",
    "│  │ - gradients   │     │  api.open-meteo.com     │  │",
    "│  │ - animations  │     │  (ฟรี ไม่ต้อง Key)      │  │",
    "│  └──────────────┘     └────────────────────────┘   │",
    "└─────────────────────────────────────────────────────┘</code></pre>",
    "",
    "<h3>🌍 Demo Features — ฟีเจอร์ทั้งหมดในแอป</h3>",
    "<ul>",
    "  <li>🗺️ <strong>เลือก 77 จังหวัดไทย</strong> จาก dropdown พร้อมพิกัดครบทุกจังหวัด</li>",
    "  <li>📍 <strong>Geolocation</strong> — กดปุ่มให้ระบุตำแหน่งอัตโนมัติ</li>",
    "  <li>🌡️ <strong>อุณหภูมิปัจจุบัน</strong> พร้อม ความเร็วลม และ ทิศทางลม</li>",
    "  <li>📅 <strong>พยากรณ์ 7 วัน</strong> แบบปัดซ้าย-ขวาบนมือถือ</li>",
    "  <li>🎆 <strong>Canvas Animation</strong> เปลี่ยนแอนิเมชันตามสภาพอากาศ</li>",
    "  <li>💾 <strong>Cache ข้อมูล</strong> ด้วย localStorage ลดการเรียก API</li>",
    "  <li>🌙 <strong>Dark Mode อัตโนมัติ</strong> ตาม System Preference</li>",
    "</ul>",
    "",
    "<h3>🖥️ Browser Compatibility — รองรับ Browser อะไรบ้าง</h3>",
    "<table>",
    "  <tr><th>Browser</th><th>Version ขั้นต่ำ</th><th>ฟีเจอร์ที่ใช้</th></tr>",
    "  <tr><td>Chrome</td><td>88+</td><td>รองรับทุกฟีเจอร์ ✅</td></tr>",
    "  <tr><td>Firefox</td><td>85+</td><td>รองรับทุกฟีเจอร์ ✅</td></tr>",
    "  <tr><td>Safari</td><td>14+</td><td>ต้องใช้ -webkit-backdrop-filter ✅</td></tr>",
    "  <tr><td>Edge</td><td>88+</td><td>รองรับทุกฟีเจอร์ ✅</td></tr>",
    "  <tr><td>IE 11</td><td>ไม่รองรับ</td><td>ใช้ ES6+ ไม่ได้ ❌</td></tr>",
    "</table>",
    "",
    "<h3>⚡ Performance Targets — เป้าหมายประสิทธิภาพ</h3>",
    "<ul>",
    "  <li>🎯 FPS: 60fps คงที่ (ใช้ requestAnimationFrame)</li>",
    "  <li>⏱️ First Load: &lt;1 วินาที (ไม่มี external libraries)</li>",
    "  <li>📡 API Response: &lt;500ms (Open-Meteo เร็วมาก)</li>",
    "  <li>💾 Cache Hit: ข้อมูลไม่เก่าเกิน 10 นาที = ใช้ cache</li>",
    "  <li>📱 Mobile: 60fps บน iPhone 12 ขึ้นไป</li>",
    "</ul>",
    "",
    "<div class='tip-box'><strong>💡</strong> Open-Meteo ให้ข้อมูลฟรีไม่จำกัด ไม่ต้องสมัคร ไม่ต้องใช้ API Key — เหมาะกับการเรียนรู้และโปรเจคส่วนตัวมากๆ!</div>",
]

# ── Chapter 1 ─────────────────────────────────────────────────────────────────

ch1 = [
    "<h2>📡 Data Fetching — ดึงข้อมูลจริงแบบไม่ง้อ API Key</h2>",
    "<p>หัวใจของการพยากรณ์อากาศคือ <strong>ข้อมูล!</strong> เราใช้ Fetch API พื้นฐานของ JavaScript ดึงข้อมูลจาก Open-Meteo API ที่ให้บริการฟรีโดยไม่ต้องสมัครสมาชิกหรือใช้ API Key ใดๆ</p>",
    "",
    "<h3>🔑 async/await คืออะไร?</h3>",
    "<p>JavaScript ทำงานแบบ Non-blocking หมายความว่าโค้ดไม่รอ — แต่เมื่อดึงข้อมูลจาก API เราต้องรอ! async/await ทำให้โค้ดอ่านง่ายเหมือนทำงาน Step-by-step:</p>",
    "<pre><code>// แบบเก่า (Callback Hell — อ่านยาก!)",
    "fetch(url).then(res => res.json()).then(data => {",
    "  // ใช้ data",
    "}).catch(err => console.error(err));",
    "",
    "// แบบใหม่ (async/await — อ่านง่ายมาก!)",
    "async function loadData() {",
    "  try {",
    "    const res = await fetch(url);   // รอจนได้ response",
    "    const data = await res.json();  // รอจน parse เสร็จ",
    "    // ใช้ data ได้เลย",
    "  } catch (err) {",
    "    console.error(err);",
    "  }",
    "}</code></pre>",
    "",
    "<h3>🌐 Open-Meteo API — Parameters ทั้งหมด</h3>",
    "<table>",
    "  <tr><th>Parameter</th><th>ค่าตัวอย่าง</th><th>ความหมาย</th></tr>",
    "  <tr><td>latitude</td><td>13.7563</td><td>ละติจูด (องศาเหนือ-ใต้)</td></tr>",
    "  <tr><td>longitude</td><td>100.5018</td><td>ลองจิจูด (องศาตะวันออก-ตะวันตก)</td></tr>",
    "  <tr><td>current_weather</td><td>true</td><td>ดึงข้อมูลสภาพอากาศปัจจุบัน</td></tr>",
    "  <tr><td>daily</td><td>weathercode,temperature_2m_max</td><td>ข้อมูลรายวัน (คั่นด้วย comma)</td></tr>",
    "  <tr><td>hourly</td><td>temperature_2m,precipitation</td><td>ข้อมูลรายชั่วโมง</td></tr>",
    "  <tr><td>forecast_days</td><td>7</td><td>จำนวนวันที่พยากรณ์ (1-16)</td></tr>",
    "  <tr><td>timezone</td><td>Asia/Bangkok</td><td>Timezone สำหรับข้อมูลวันที่/เวลา</td></tr>",
    "  <tr><td>wind_speed_unit</td><td>kmh</td><td>หน่วยความเร็วลม (kmh/ms/mph/kn)</td></tr>",
    "  <tr><td>temperature_unit</td><td>celsius</td><td>หน่วยอุณหภูมิ (celsius/fahrenheit)</td></tr>",
    "  <tr><td>precipitation_unit</td><td>mm</td><td>หน่วยปริมาณน้ำฝน (mm/inch)</td></tr>",
    "</table>",
    "",
    "<h3>📍 จังหวัดไทยทั้ง 77 จังหวัด พร้อมพิกัด</h3>",
    "<pre><code>const PROVINCES = {",
    "  // ภาคกลาง",
    "  'กรุงเทพมหานคร': { lat: 13.7563, lng: 100.5018 },",
    "  'นนทบุรี':        { lat: 11.5844, lng: 100.0583 },",
    "  'ปทุมธานี':       { lat: 14.0208, lng: 100.5250 },",
    "  'สมุทรปราการ':    { lat: 13.5990, lng: 100.5998 },",
    "  'นครปฐม':         { lat: 13.8196, lng: 100.0645 },",
    "  'สมุทรสาคร':      { lat: 13.5475, lng: 100.2747 },",
    "  'สมุทรสงคราม':    { lat: 13.4098, lng: 100.0020 },",
    "  'อ่างทอง':        { lat: 14.5896, lng: 100.4550 },",
    "  'พระนครศรีอยุธยา':{ lat: 14.3692, lng: 100.5877 },",
    "  'ลพบุรี':          { lat: 14.7995, lng: 100.6534 },",
    "  'สระบุรี':         { lat: 14.5289, lng: 100.9106 },",
    "  'สิงห์บุรี':       { lat: 14.8936, lng: 100.3966 },",
    "  'ชัยนาท':          { lat: 15.1851, lng: 100.1251 },",
    "  'สุพรรณบุรี':      { lat: 14.4744, lng: 100.1177 },",
    "  'กาญจนบุรี':       { lat: 14.0023, lng: 99.5328 },",
    "  'ราชบุรี':         { lat: 13.5282, lng: 99.8134 },",
    "  'เพชรบุรี':        { lat: 13.1119, lng: 99.9390 },",
    "  'ประจวบคีรีขันธ์': { lat: 11.8126, lng: 99.7975 },",
    "  // ภาคเหนือ",
    "  'เชียงใหม่':       { lat: 18.7883, lng: 98.9853 },",
    "  'เชียงราย':        { lat: 19.9105, lng: 99.8407 },",
    "  'แม่ฮ่องสอน':     { lat: 19.3020, lng: 97.9654 },",
    "  'ลำพูน':           { lat: 18.5744, lng: 99.0087 },",
    "  'ลำปาง':           { lat: 18.2888, lng: 99.4909 },",
    "  'แพร่':            { lat: 18.1446, lng: 100.1405 },",
    "  'น่าน':            { lat: 18.7756, lng: 100.7730 },",
    "  'พะเยา':           { lat: 19.1664, lng: 99.9019 },",
    "  'ตาก':             { lat: 16.8840, lng: 99.1258 },",
    "  'สุโขทัย':         { lat: 17.0100, lng: 99.8232 },",
    "  'อุตรดิตถ์':       { lat: 17.6200, lng: 100.0993 },",
    "  'พิษณุโลก':        { lat: 16.8211, lng: 100.2659 },",
    "  'พิจิตร':          { lat: 16.4419, lng: 100.3487 },",
    "  'กำแพงเพชร':       { lat: 16.4827, lng: 99.5226 },",
    "  'นครสวรรค์':       { lat: 15.7030, lng: 100.1370 },",
    "  'อุทัยธานี':       { lat: 15.3835, lng: 100.0255 },",
    "  // ภาคตะวันออกเฉียงเหนือ",
    "  'ขอนแก่น':         { lat: 16.4419, lng: 102.8360 },",
    "  'อุดรธานี':        { lat: 17.4138, lng: 102.7872 },",
    "  'หนองคาย':         { lat: 17.8783, lng: 102.7423 },",
    "  'นครพนม':          { lat: 17.3923, lng: 104.7731 },",
    "  'สกลนคร':          { lat: 17.1547, lng: 104.1348 },",
    "  'มุกดาหาร':        { lat: 16.5432, lng: 104.7236 },",
    "  'กาฬสินธุ์':       { lat: 16.4336, lng: 103.5060 },",
    "  'มหาสารคาม':       { lat: 16.1851, lng: 103.3003 },",
    "  'ร้อยเอ็ด':        { lat: 16.0538, lng: 103.6520 },",
    "  'ยโสธร':           { lat: 15.7922, lng: 104.1453 },",
    "  'อุบลราชธานี':     { lat: 15.2287, lng: 104.8593 },",
    "  'อำนาจเจริญ':      { lat: 15.8656, lng: 104.6257 },",
    "  'ศรีสะเกษ':        { lat: 15.1186, lng: 104.3220 },",
    "  'สุรินทร์':        { lat: 14.8824, lng: 103.4930 },",
    "  'บุรีรัมย์':       { lat: 14.9930, lng: 103.1029 },",
    "  'นครราชสีมา':      { lat: 14.9799, lng: 102.0978 },",
    "  'ชัยภูมิ':         { lat: 15.8068, lng: 102.0317 },",
    "  'เลย':             { lat: 17.4860, lng: 101.7223 },",
    "  'หนองบัวลำภู':     { lat: 17.2040, lng: 102.4410 },",
    "  'บึงกาฬ':          { lat: 18.3609, lng: 103.6519 },",
    "  // ภาคตะวันออก",
    "  'ชลบุรี':          { lat: 13.3611, lng: 100.9847 },",
    "  'ระยอง':           { lat: 12.6814, lng: 101.2816 },",
    "  'จันทบุรี':        { lat: 12.6095, lng: 102.1039 },",
    "  'ตราด':            { lat: 12.2427, lng: 102.5175 },",
    "  'ฉะเชิงเทรา':      { lat: 13.6904, lng: 101.0779 },",
    "  'ปราจีนบุรี':      { lat: 14.0521, lng: 101.3700 },",
    "  'สระแก้ว':         { lat: 13.8248, lng: 102.0642 },",
    "  'นครนายก':         { lat: 14.2069, lng: 101.2131 },",
    "  // ภาคใต้",
    "  'สุราษฎร์ธานี':    { lat: 9.1382, lng: 99.3144 },",
    "  'ภูเก็ต':          { lat: 7.8804, lng: 98.3923 },",
    "  'กระบี่':          { lat: 8.0863, lng: 98.9063 },",
    "  'พังงา':           { lat: 8.4510, lng: 98.5250 },",
    "  'ระนอง':           { lat: 9.9529, lng: 98.6084 },",
    "  'ชุมพร':           { lat: 10.4930, lng: 99.1800 },",
    "  'นครศรีธรรมราช':   { lat: 8.4321, lng: 99.9630 },",
    "  'ตรัง':            { lat: 7.5591, lng: 99.6113 },",
    "  'พัทลุง':          { lat: 7.6167, lng: 100.0743 },",
    "  'สงขลา':           { lat: 7.1756, lng: 100.6143 },",
    "  'สตูล':            { lat: 6.6238, lng: 100.0671 },",
    "  'ปัตตานี':         { lat: 6.8691, lng: 101.2509 },",
    "  'ยะลา':            { lat: 6.5415, lng: 101.2800 },",
    "  'นราธิวาส':        { lat: 6.4254, lng: 101.8253 },",
    "};",
    "</code></pre>",
    "",
    "<h3>📡 Geolocation API — ระบุตำแหน่งจาก GPS</h3>",
    "<pre><code>function getCurrentLocation() {",
    "  return new Promise((resolve, reject) => {",
    "    if (!navigator.geolocation) {",
    "      reject('Browser นี้ไม่รองรับ Geolocation');",
    "      return;",
    "    }",
    "    navigator.geolocation.getCurrentPosition(",
    "      (pos) => resolve({",
    "        lat: pos.coords.latitude,",
    "        lng: pos.coords.longitude,",
    "        accuracy: pos.coords.accuracy,  // ความแม่นยำ (เมตร)",
    "      }),",
    "      (err) => {",
    "        const msgs = {",
    "          1: 'ผู้ใช้ปฏิเสธการระบุตำแหน่ง',",
    "          2: 'ไม่สามารถระบุตำแหน่งได้',",
    "          3: 'หมดเวลา',",
    "        };",
    "        reject(msgs[err.code] || 'เกิดข้อผิดพลาด');",
    "      },",
    "      { timeout: 10000, maximumAge: 60000 }  // options",
    "    );",
    "  });",
    "}</code></pre>",
    "",
    "<h3>🔄 Error Handling + Retry + Cache</h3>",
    "<pre><code>const CACHE_KEY = 'weather_cache';",
    "const CACHE_DURATION = 10 * 60 * 1000;  // 10 นาที",
    "",
    "function getCachedWeather(lat, lng) {",
    "  try {",
    "    const raw = localStorage.getItem(CACHE_KEY);",
    "    if (!raw) return null;",
    "    const { data, timestamp, location } = JSON.parse(raw);",
    "    if (location.lat !== lat || location.lng !== lng) return null;",
    "    if (Date.now() - timestamp > CACHE_DURATION) return null;",
    "    return data;  // cache ยังสด!",
    "  } catch { return null; }",
    "}",
    "",
    "function setCachedWeather(lat, lng, data) {",
    "  localStorage.setItem(CACHE_KEY, JSON.stringify({",
    "    data, timestamp: Date.now(), location: { lat, lng }",
    "  }));",
    "}",
    "",
    "async function fetchWeatherWithRetry(lat, lng, retries = 3) {",
    "  // ลอง cache ก่อน",
    "  const cached = getCachedWeather(lat, lng);",
    "  if (cached) { console.log('✅ ใช้ cache'); return cached; }",
    "",
    "  for (let i = 0; i < retries; i++) {",
    "    try {",
    "      const params = new URLSearchParams({",
    "        latitude: lat, longitude: lng,",
    "        current_weather: true,",
    "        daily: 'weathercode,temperature_2m_max,temperature_2m_min,precipitation_sum',",
    "        hourly: 'temperature_2m,precipitation_probability',",
    "        forecast_days: 7,",
    "        timezone: 'Asia/Bangkok',",
    "        wind_speed_unit: 'kmh',",
    "      });",
    "      const res = await fetch(",
    "        'https://api.open-meteo.com/v1/forecast?' + params",
    "      );",
    "      if (!res.ok) throw new Error('HTTP ' + res.status);",
    "      const data = await res.json();",
    "      setCachedWeather(lat, lng, data);  // บันทึก cache",
    "      return data;",
    "    } catch (err) {",
    "      if (i === retries - 1) throw err;  // retry หมดแล้ว",
    "      await new Promise(r => setTimeout(r, 1000 * (i + 1)));  // รอ 1,2,3 วิ",
    "    }",
    "  }",
    "}</code></pre>",
    "",
    "<h3>🌤️ WMO Weather Code — ทุก Code 0-99 แปลเป็นไทย</h3>",
    "<pre><code>const WMO_CODES = {",
    "  // Clear sky",
    "  0:  { text: 'ฟ้าใส',              emoji: '☀️',  type: 'sunny' },",
    "  // Mainly clear, partly cloudy, overcast",
    "  1:  { text: 'ท้องฟ้าโปร่งบางส่วน', emoji: '🌤️', type: 'cloudy' },",
    "  2:  { text: 'มีเมฆบางส่วน',        emoji: '⛅',  type: 'cloudy' },",
    "  3:  { text: 'เมฆมากปกคลุม',        emoji: '☁️',  type: 'cloudy' },",
    "  // Fog",
    "  45: { text: 'หมอกปกคลุม',          emoji: '🌫️', type: 'fog' },",
    "  48: { text: 'หมอกแข็งตัว',         emoji: '🌫️', type: 'fog' },",
    "  // Drizzle",
    "  51: { text: 'ฝนปรอยเบา',           emoji: '🌦️', type: 'rain' },",
    "  53: { text: 'ฝนปรอยปานกลาง',       emoji: '🌦️', type: 'rain' },",
    "  55: { text: 'ฝนปรอยหนัก',          emoji: '🌦️', type: 'rain' },",
    "  56: { text: 'ฝนปรอยแข็งตัวเบา',    emoji: '🌨️', type: 'snow' },",
    "  57: { text: 'ฝนปรอยแข็งตัวหนัก',   emoji: '🌨️', type: 'snow' },",
    "  // Rain",
    "  61: { text: 'ฝนตกเบา',             emoji: '🌧️', type: 'rain' },",
    "  63: { text: 'ฝนตกปานกลาง',         emoji: '🌧️', type: 'rain' },",
    "  65: { text: 'ฝนตกหนัก',            emoji: '🌧️', type: 'rain' },",
    "  66: { text: 'ฝนแข็งตัวเบา',        emoji: '🌨️', type: 'snow' },",
    "  67: { text: 'ฝนแข็งตัวหนัก',       emoji: '🌨️', type: 'snow' },",
    "  // Snow",
    "  71: { text: 'หิมะตกเบา',           emoji: '❄️',  type: 'snow' },",
    "  73: { text: 'หิมะตกปานกลาง',       emoji: '❄️',  type: 'snow' },",
    "  75: { text: 'หิมะตกหนัก',          emoji: '❄️',  type: 'snow' },",
    "  77: { text: 'เกล็ดหิมะ',           emoji: '🌨️', type: 'snow' },",
    "  // Rain showers",
    "  80: { text: 'ฝนซาเบา',             emoji: '🌦️', type: 'rain' },",
    "  81: { text: 'ฝนซาปานกลาง',         emoji: '🌦️', type: 'rain' },",
    "  82: { text: 'ฝนซารุนแรง',          emoji: '🌧️', type: 'rain' },",
    "  // Snow showers",
    "  85: { text: 'หิมะซาเบา',           emoji: '🌨️', type: 'snow' },",
    "  86: { text: 'หิมะซาหนัก',          emoji: '🌨️', type: 'snow' },",
    "  // Thunderstorm",
    "  95: { text: 'พายุฝนฟ้าคะนอง',      emoji: '⛈️', type: 'storm' },",
    "  96: { text: 'พายุฝนฟ้าคะนองและลูกเห็บเบา', emoji: '⛈️', type: 'storm' },",
    "  99: { text: 'พายุฝนฟ้าคะนองและลูกเห็บหนัก', emoji: '⛈️', type: 'storm' },",
    "};",
    "",
    "function getWeatherInfo(code) {",
    "  return WMO_CODES[code] || { text: 'ไม่ทราบสภาพอากาศ', emoji: '❓', type: 'sunny' };",
    "}</code></pre>",
    "",
    "<div class='tip-box'><strong>💡</strong> ใช้ async/await + try/catch + retry + localStorage cache = ระบบดึงข้อมูลที่แข็งแกร่งมาก แม้เน็ตหลุดก็ยังโชว์ข้อมูลเก่าได้!</div>",
]

# ── Chapter 2 ─────────────────────────────────────────────────────────────────

ch2 = [
    "<h2>🎨 Glassmorphism UI — สวยด้วย CSS ล้วนๆ ไม่ง้อ Framework</h2>",
    "<p>หน้าตาที่ดูคลีน ทันสมัย และน่าใช้งาน เกิดจาก <strong>CSS ล้วนๆ</strong> ไม่ต้องพึ่ง TailwindCSS, Bootstrap หรือ Framework ใดๆ! เราจะสร้าง Design System ตั้งแต่ CSS Variables ไปจนถึง Animation Keyframes</p>",
    "",
    "<h3>🎨 CSS Design System — CSS Variables</h3>",
    "<pre><code>/* ── Color Tokens ── */",
    ":root {",
    "  /* Weather Type Colors */",
    "  --sunny-from:  #74b9ff;  --sunny-mid:  #fdcb6e;  --sunny-to:  #fd79a8;",
    "  --cloudy-from: #b2bec3;  --cloudy-mid: #636e72;  --cloudy-to: #dfe6e9;",
    "  --rain-from:   #636e72;  --rain-mid:   #2d3436;  --rain-to:   #74b9ff;",
    "  --storm-from:  #2d3436;  --storm-mid:  #6c5ce7;  --storm-to:  #000000;",
    "  --fog-from:    #dfe6e9;  --fog-mid:    #b2bec3;  --fog-to:    #636e72;",
    "  --snow-from:   #dfe6e9;  --snow-mid:   #74b9ff;  --snow-to:   #a29bfe;",
    "",
    "  /* Glass Effect */",
    "  --glass-bg:     rgba(255, 255, 255, 0.75);",
    "  --glass-border: rgba(255, 255, 255, 0.3);",
    "  --glass-blur:   25px;",
    "  --glass-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);",
    "",
    "  /* Dark Mode Glass */",
    "  --glass-dark-bg: rgba(0, 0, 0, 0.4);",
    "  --glass-dark-border: rgba(255, 255, 255, 0.1);",
    "",
    "  /* Spacing Scale */",
    "  --sp-1: 4px;  --sp-2: 8px;  --sp-3: 12px;",
    "  --sp-4: 16px; --sp-5: 20px; --sp-6: 24px;",
    "  --sp-8: 32px; --sp-10: 40px; --sp-12: 48px;",
    "",
    "  /* Typography */",
    "  --font-base: 'Prompt', 'Noto Sans Thai', sans-serif;",
    "  --text-xs: 12px; --text-sm: 14px; --text-base: 16px;",
    "  --text-lg: 18px; --text-xl: 24px; --text-2xl: 32px;",
    "  --text-4xl: 48px; --text-6xl: 72px;",
    "",
    "  /* Border Radius */",
    "  --radius-sm: 8px; --radius-md: 12px;",
    "  --radius-lg: 20px; --radius-xl: 28px;",
    "",
    "  /* Transition */",
    "  --ease: 0.3s cubic-bezier(0.4, 0, 0.2, 1);",
    "}</code></pre>",
    "",
    "<h3>💎 Glass Card — Glassmorphism Effect</h3>",
    "<pre><code>/* Glass Card หลัก */",
    ".weather-card {",
    "  background: var(--glass-bg);",
    "  backdrop-filter: blur(var(--glass-blur));",
    "  -webkit-backdrop-filter: blur(var(--glass-blur));",
    "  border: 1px solid var(--glass-border);",
    "  border-radius: var(--radius-xl);",
    "  box-shadow: var(--glass-shadow);",
    "  padding: var(--sp-8);",
    "  max-width: 420px;",
    "  width: 100%;",
    "  text-align: center;",
    "  transition: transform var(--ease), box-shadow var(--ease);",
    "}",
    "",
    ".weather-card:hover {",
    "  transform: translateY(-4px);",
    "  box-shadow: 0 16px 48px rgba(0, 0, 0, 0.15);",
    "}</code></pre>",
    "",
    "<h3>🌈 Weather Gradient Backgrounds</h3>",
    "<pre><code>/* แต่ละ weather type มี palette ของตัวเอง */",
    ".body-sunny  { background: linear-gradient(135deg, #74b9ff 0%, #fdcb6e 60%, #fd79a8 100%); }",
    ".body-cloudy { background: linear-gradient(135deg, #dfe6e9 0%, #b2bec3 50%, #636e72 100%); }",
    ".body-rain   { background: linear-gradient(135deg, #636e72 0%, #2d3436 60%, #4a69bd 100%); }",
    ".body-storm  { background: linear-gradient(135deg, #2d3436 0%, #6c5ce7 50%, #000000 100%); }",
    ".body-fog    { background: linear-gradient(135deg, #dfe6e9 0%, #b2bec3 50%, #636e72 100%); }",
    ".body-snow   { background: linear-gradient(135deg, #dfe6e9 0%, #74b9ff 50%, #a29bfe 100%); }",
    "",
    "/* Smooth transition เมื่อเปลี่ยนสภาพอากาศ */",
    "body { transition: background var(--ease); }</code></pre>",
    "",
    "<h3>✨ Animation Keyframes ทั้งหมด</h3>",
    "<pre><code>/* Fade In — สำหรับ card เข้าหน้าจอ */",
    "@keyframes fadeIn {",
    "  from { opacity: 0; transform: translateY(20px); }",
    "  to   { opacity: 1; transform: translateY(0); }",
    "}",
    "",
    "/* Pulse — สำหรับปุ่ม loading */",
    "@keyframes pulse {",
    "  0%, 100% { transform: scale(1); }",
    "  50%       { transform: scale(1.05); }",
    "}",
    "",
    "/* Float — สำหรับ emoji ลอยๆ */",
    "@keyframes float {",
    "  0%, 100% { transform: translateY(0px); }",
    "  50%       { transform: translateY(-10px); }",
    "}",
    "",
    "/* Spin — สำหรับ loading spinner */",
    "@keyframes spin {",
    "  from { transform: rotate(0deg); }",
    "  to   { transform: rotate(360deg); }",
    "}",
    "",
    "/* Shimmer — สำหรับ skeleton loading */",
    "@keyframes shimmer {",
    "  0%   { background-position: -200% 0; }",
    "  100% { background-position: 200% 0; }",
    "}",
    "",
    "/* ใช้งาน */",
    ".weather-card   { animation: fadeIn 0.5s var(--ease); }",
    ".weather-emoji  { animation: float 3s ease-in-out infinite; }",
    ".loading-spinner{ animation: spin 1s linear infinite; }</code></pre>",
    "",
    "<h3>💀 Skeleton Loading — ขณะรอข้อมูล</h3>",
    "<pre><code>/* Skeleton placeholder */",
    ".skeleton {",
    "  background: linear-gradient(",
    "    90deg,",
    "    rgba(255,255,255,0.1) 0%,",
    "    rgba(255,255,255,0.3) 50%,",
    "    rgba(255,255,255,0.1) 100%",
    "  );",
    "  background-size: 200% 100%;",
    "  animation: shimmer 1.5s infinite;",
    "  border-radius: var(--radius-sm);",
    "}",
    "",
    ".skeleton-temp  { width: 120px; height: 72px; margin: 0 auto; }",
    ".skeleton-text  { width: 180px; height: 20px; margin: 8px auto; }",
    ".skeleton-small { width: 100px; height: 16px; margin: 4px auto; }</code></pre>",
    "",
    "<h3>🌙 Dark Mode — ตาม System Preference</h3>",
    "<pre><code>@media (prefers-color-scheme: dark) {",
    "  .weather-card {",
    "    background: var(--glass-dark-bg);",
    "    border-color: var(--glass-dark-border);",
    "    color: #ffffff;",
    "  }",
    "  .temp, .location-name { color: #ffffff; }",
    "  .desc { color: rgba(255,255,255,0.8); }",
    "  .forecast-card {",
    "    background: rgba(0,0,0,0.3);",
    "    border-color: rgba(255,255,255,0.1);",
    "  }",
    "}</code></pre>",
    "",
    "<h3>📱 Mobile Breakpoints — Responsive ทุกขนาด</h3>",
    "<pre><code>/* Mobile Small: 320px */",
    "@media (max-width: 360px) {",
    "  .weather-card { padding: var(--sp-5); }",
    "  .temp { font-size: var(--text-4xl); }",
    "  .weather-emoji { font-size: 48px; }",
    "}",
    "",
    "/* Mobile: 375-767px */",
    "@media (max-width: 767px) {",
    "  .app-container { padding: var(--sp-4); }",
    "  .weather-card  { padding: var(--sp-6); }",
    "  .forecast-grid { display: flex; overflow-x: auto; }",
    "}",
    "",
    "/* Tablet: 768-1023px */",
    "@media (min-width: 768px) and (max-width: 1023px) {",
    "  .weather-card { max-width: 520px; }",
    "  .temp { font-size: var(--text-6xl); }",
    "}",
    "",
    "/* Desktop: 1024px+ */",
    "@media (min-width: 1024px) {",
    "  .app-container { flex-direction: row; gap: 32px; }",
    "  .weather-card  { max-width: 400px; }",
    "  .forecast-section { flex: 1; }",
    "}</code></pre>",
    "",
    "<h3>♿ Accessibility — ARIA + Focus Styles</h3>",
    "<pre><code>/* Focus visible สำหรับ keyboard navigation */",
    ".province-select:focus-visible,",
    "button:focus-visible {",
    "  outline: 3px solid #74b9ff;",
    "  outline-offset: 2px;",
    "}",
    "",
    "/* Skip to main content */",
    ".skip-link {",
    "  position: absolute; top: -40px; left: 0;",
    "  background: #74b9ff; color: white;",
    "  padding: 8px; z-index: 9999;",
    "  transition: top 0.2s;",
    "}",
    ".skip-link:focus { top: 0; }</code></pre>",
    "",
    "<pre><code>&lt;!-- ARIA Labels ที่ควรใส่ --&gt;",
    "&lt;canvas aria-hidden='true'&gt;&lt;/canvas&gt;",
    "&lt;main role='main' aria-label='ข้อมูลพยากรณ์อากาศ'&gt;",
    "  &lt;select id='provinceSelect' aria-label='เลือกจังหวัด'&gt;&lt;/select&gt;",
    "  &lt;div aria-live='polite' aria-atomic='true' id='weatherInfo'&gt;",
    "    &lt;!-- ข้อมูลอากาศ update ตรงนี้ --&gt;",
    "  &lt;/div&gt;",
    "&lt;/main&gt;</code></pre>",
    "",
    "<div class='tip-box'><strong>💡</strong> CSS Variables (Custom Properties) ทำให้ theme เปลี่ยนง่ายมาก — แค่เปลี่ยนค่าใน :root เดียว ทุกอย่างอัพเดตเอง!</div>",
]

# ── Chapter 3 ─────────────────────────────────────────────────────────────────

ch3 = [
    "<h2>✨ HTML5 Canvas — แอนิเมชัน 60FPS พระเอกของเรา!</h2>",
    "<p>พื้นหลังที่เปลี่ยนสีและมีแอนิเมชันตามสภาพอากาศ <strong>ไม่ได้ใช้ Video หรือ GIF</strong> แต่วาดด้วยคณิตศาสตร์และโค้ดแบบเฟรมต่อเฟรมด้วย HTML5 Canvas API — ทำให้ควบคุมทุก pixel บนหน้าจอได้อย่างสมบูรณ์!</p>",
    "",
    "<h3>📐 Canvas Coordinate System — ระบบพิกัด</h3>",
    "<pre><code>// Canvas ใช้พิกัด (0,0) ที่มุมบน-ซ้าย",
    "//  x → เพิ่มไปทางขวา",
    "//  y ↓ เพิ่มลงด้านล่าง",
    "//",
    "// (0,0) ──────────────── (width, 0)",
    "//   |                          |",
    "//   |      Canvas Area         |",
    "//   |                          |",
    "// (0,height) ───── (width, height)",
    "",
    "const canvas = document.getElementById('weatherCanvas');",
    "const ctx = canvas.getContext('2d');  // 2D context",
    "",
    "// วาดสี่เหลี่ยม",
    "ctx.fillStyle = 'red';",
    "ctx.fillRect(x, y, width, height);",
    "",
    "// วาดวงกลม",
    "ctx.beginPath();",
    "ctx.arc(centerX, centerY, radius, startAngle, endAngle);",
    "ctx.fill();",
    "",
    "// วาดเส้น",
    "ctx.beginPath();",
    "ctx.moveTo(x1, y1);",
    "ctx.lineTo(x2, y2);",
    "ctx.stroke();</code></pre>",
    "",
    "<h3>📱 Device Pixel Ratio — Retina Display Sharp</h3>",
    "<pre><code>function setupHiDPICanvas(canvas) {",
    "  const dpr = window.devicePixelRatio || 1;",
    "  const rect = canvas.getBoundingClientRect();",
    "",
    "  // ขนาดจริงของ canvas (pixel จริงบนหน้าจอ Retina)",
    "  canvas.width  = rect.width  * dpr;",
    "  canvas.height = rect.height * dpr;",
    "",
    "  // CSS size ยังคงเท่าเดิม",
    "  canvas.style.width  = rect.width  + 'px';",
    "  canvas.style.height = rect.height + 'px';",
    "",
    "  // Scale context ให้ตรงกับ DPR",
    "  ctx.scale(dpr, dpr);",
    "",
    "  return { width: rect.width, height: rect.height, dpr };",
    "}",
    "",
    "// Resize handler",
    "function resizeCanvas() {",
    "  canvas.style.width  = window.innerWidth  + 'px';",
    "  canvas.style.height = window.innerHeight + 'px';",
    "  setupHiDPICanvas(canvas);",
    "  // วาดใหม่ทันที",
    "  drawFrame();",
    "}",
    "window.addEventListener('resize', resizeCanvas);",
    "resizeCanvas();</code></pre>",
    "",
    "<h3>🌈 Gradient Types — Linear vs Radial</h3>",
    "<pre><code>// ── Linear Gradient (ท้องฟ้า) ──",
    "function drawSkyGradient(type) {",
    "  const palettes = {",
    "    sunny:  [['#74b9ff', 0], ['#fdcb6e', 0.6], ['#fd79a8', 1]],",
    "    cloudy: [['#dfe6e9', 0], ['#b2bec3', 0.5], ['#636e72', 1]],",
    "    rain:   [['#636e72', 0], ['#2d3436', 0.5], ['#4a69bd', 1]],",
    "    storm:  [['#2d3436', 0], ['#6c5ce7', 0.5], ['#000', 1]],",
    "    fog:    [['#dfe6e9', 0], ['#b2bec3', 0.5], ['#95a5a6', 1]],",
    "    snow:   [['#dfe6e9', 0], ['#74b9ff', 0.5], ['#a29bfe', 1]],",
    "  };",
    "  const stops = palettes[type] || palettes.sunny;",
    "",
    "  const grad = ctx.createLinearGradient(0, 0, 0, canvas.height / dpr);",
    "  stops.forEach(([color, pos]) => grad.addColorStop(pos, color));",
    "  ctx.fillStyle = grad;",
    "  ctx.fillRect(0, 0, canvas.width / dpr, canvas.height / dpr);",
    "}",
    "",
    "// ── Radial Gradient (ดวงอาทิตย์/ดวงจันทร์) ──",
    "function drawSunGlow(x, y, radius) {",
    "  const grad = ctx.createRadialGradient(x, y, 0, x, y, radius);",
    "  grad.addColorStop(0,   'rgba(253,203,110,1.0)');",
    "  grad.addColorStop(0.4, 'rgba(253,203,110,0.6)');",
    "  grad.addColorStop(0.8, 'rgba(253,203,110,0.1)');",
    "  grad.addColorStop(1,   'rgba(253,203,110,0.0)');",
    "  ctx.fillStyle = grad;",
    "  ctx.beginPath();",
    "  ctx.arc(x, y, radius, 0, Math.PI * 2);",
    "  ctx.fill();",
    "}</code></pre>",
    "",
    "<h3>⚡ Performance Optimization</h3>",
    "<pre><code>// ── Object Pooling (ลด GC pressure) ──",
    "const particlePool = [];",
    "",
    "function getParticle() {",
    "  return particlePool.pop() || {};  // นำกลับมาใช้ ไม่สร้างใหม่",
    "}",
    "",
    "function releaseParticle(p) {",
    "  particlePool.push(p);  // คืน pool แทนการทิ้ง",
    "}",
    "",
    "// ── Offscreen Canvas (วาดซับซ้อนนอก main thread) ──",
    "const offscreen = document.createElement('canvas');",
    "const offCtx = offscreen.getContext('2d');",
    "",
    "// วาดสิ่งที่ไม่เปลี่ยนแปลงบ่อยไว้ที่ offscreen",
    "function drawStaticLayer() {",
    "  offCtx.clearRect(0, 0, offscreen.width, offscreen.height);",
    "  // วาด background, stars ฯลฯ",
    "  drawStars(offCtx);",
    "}",
    "",
    "// ใน main loop แค่ blit offscreen มา",
    "function animate() {",
    "  ctx.drawImage(offscreen, 0, 0);  // เร็วกว่าวาดใหม่มาก!",
    "  // วาดเฉพาะส่วนที่เคลื่อนไหว",
    "  particles.forEach(p => p.draw(ctx));",
    "  requestAnimationFrame(animate);",
    "}</code></pre>",
    "",
    "<h3>📊 FPS Counter — วัดประสิทธิภาพ</h3>",
    "<pre><code>class FPSCounter {",
    "  constructor() {",
    "    this.frames = [];",
    "    this.lastTime = performance.now();",
    "  }",
    "",
    "  tick() {",
    "    const now = performance.now();",
    "    this.frames.push(now);",
    "    // เก็บเฉพาะ 1 วินาทีล่าสุด",
    "    while (this.frames[0] <= now - 1000) {",
    "      this.frames.shift();",
    "    }",
    "    return this.frames.length;  // = FPS",
    "  }",
    "}",
    "",
    "const fps = new FPSCounter();",
    "",
    "function animate() {",
    "  const currentFPS = fps.tick();",
    "",
    "  // แสดง FPS บน canvas (สำหรับ debug)",
    "  ctx.fillStyle = 'rgba(255,255,255,0.8)';",
    "  ctx.font = '14px monospace';",
    "  ctx.fillText('FPS: ' + currentFPS, 10, 20);",
    "",
    "  // ... วาดอื่นๆ",
    "  requestAnimationFrame(animate);",
    "}</code></pre>",
    "",
    "<h3>🔄 Complete Animation Loop</h3>",
    "<pre><code>let particles = [];",
    "let currentWeather = 'sunny';",
    "let animId = null;",
    "const fpsCounter = new FPSCounter();",
    "",
    "function animate(timestamp) {",
    "  // 1. Performance metrics",
    "  const fps = fpsCounter.tick();",
    "",
    "  // 2. ล้างหน้าจอ",
    "  ctx.clearRect(0, 0, canvas.width / dpr, canvas.height / dpr);",
    "",
    "  // 3. วาดท้องฟ้า (gradient)",
    "  drawSkyGradient(currentWeather);",
    "",
    "  // 4. อัพเดทและวาดอนุภาค",
    "  for (let i = particles.length - 1; i >= 0; i--) {",
    "    const p = particles[i];",
    "    p.update();",
    "    p.draw(ctx);",
    "    if (!p.isAlive()) {",
    "      releaseParticle(p);",
    "      particles.splice(i, 1);  // ลบ dead particles",
    "    }",
    "  }",
    "",
    "  // 5. Spawn อนุภาคใหม่",
    "  spawnParticles(currentWeather);",
    "",
    "  // 6. Debug overlay",
    "  if (DEBUG_MODE) {",
    "    ctx.fillStyle = 'rgba(0,0,0,0.5)';",
    "    ctx.fillRect(8, 8, 140, 56);",
    "    ctx.fillStyle = '#fff';",
    "    ctx.font = '12px monospace';",
    "    ctx.fillText('FPS: ' + fps, 16, 24);",
    "    ctx.fillText('Particles: ' + particles.length, 16, 40);",
    "    ctx.fillText('Weather: ' + currentWeather, 16, 56);",
    "  }",
    "",
    "  // 7. Loop!",
    "  animId = requestAnimationFrame(animate);",
    "}",
    "",
    "// เริ่ม",
    "function startAnimation(weatherType) {",
    "  if (animId) cancelAnimationFrame(animId);",
    "  particles = [];",
    "  currentWeather = weatherType;",
    "  animate(performance.now());",
    "}</code></pre>",
    "",
    "<div class='tip-box'><strong>💡</strong> requestAnimationFrame จะหยุดทำงานอัตโนมัติเมื่อ tab ไม่ active — ช่วยประหยัดแบตมือถือ และ CPU ของผู้ใช้ได้มาก!</div>",
]

# ── Chapter 4 ─────────────────────────────────────────────────────────────────

ch4 = [
    "<h2>🎆 Particle System OOP — ระบบอนุภาคสมบูรณ์</h2>",
    "<p>เราออกแบบ <strong>Particle System แบบ OOP</strong> โดยใช้ Base Class และ Subclass สำหรับแต่ละสภาพอากาศ ทำให้โค้ดสะอาด ขยายได้ง่าย และจัดการ Memory ได้ดี</p>",
    "",
    "<h3>🏗️ Base Particle Class</h3>",
    "<pre><code>class Particle {",
    "  constructor(canvas) {",
    "    this.canvas = canvas;",
    "    this.W = canvas.width  / (window.devicePixelRatio || 1);",
    "    this.H = canvas.height / (window.devicePixelRatio || 1);",
    "    this.dead = false;",
    "    this.init();",
    "  }",
    "",
    "  // Subclass override เพื่อ initialize properties",
    "  init() {}",
    "",
    "  // Subclass override เพื่ออัพเดทตำแหน่ง/สถานะ",
    "  update() {}",
    "",
    "  // Subclass override เพื่อวาดตัวเอง",
    "  draw(ctx) {}",
    "",
    "  isAlive() { return !this.dead; }",
    "",
    "  // Helper: สุ่มตัวเลข",
    "  rand(min, max) { return min + Math.random() * (max - min); }",
    "",
    "  // Helper: clamp ค่า",
    "  clamp(v, min, max) { return Math.min(Math.max(v, min), max); }",
    "}</code></pre>",
    "",
    "<h3>🌧️ RainParticle — เม็ดฝนตกแบบ Physics</h3>",
    "<pre><code>class RainParticle extends Particle {",
    "  init() {",
    "    this.x      = this.rand(0, this.W);",
    "    this.y      = this.rand(-50, -10);",
    "    this.length = this.rand(10, 25);",
    "    this.speed  = this.rand(6, 14);",
    "    this.wind   = this.rand(-0.5, -2);  // ลมพัดเฉียง",
    "    this.opacity= this.rand(0.2, 0.6);",
    "    this.weight = this.rand(1, 2.5);    // น้ำหนักเม็ดฝน",
    "  }",
    "",
    "  update() {",
    "    this.y += this.speed;",
    "    this.x += this.wind;",
    "    // แรงโน้มถ่วง — เม็ดฝนเร็วขึ้นเรื่อยๆ",
    "    this.speed  = Math.min(this.speed + 0.05, 16);",
    "    if (this.y > this.H + 20) this.dead = true;",
    "  }",
    "",
    "  draw(ctx) {",
    "    ctx.save();",
    "    ctx.strokeStyle = 'rgba(174, 214, 241, ' + this.opacity + ')';",
    "    ctx.lineWidth = this.weight;",
    "    ctx.lineCap = 'round';",
    "    ctx.beginPath();",
    "    ctx.moveTo(this.x, this.y);",
    "    ctx.lineTo(this.x + this.wind * 3, this.y + this.length);",
    "    ctx.stroke();",
    "    ctx.restore();",
    "  }",
    "}",
    "",
    "// Spawn rate: ฝนตกหนัก = spawn เร็ว",
    "const RAIN_SPAWN = { 'light': 3, 'medium': 6, 'heavy': 12 };</code></pre>",
    "",
    "<h3>☁️ CloudParticle — ก้อนเมฆลอยนุ่มๆ</h3>",
    "<pre><code>class CloudParticle extends Particle {",
    "  init() {",
    "    this.x       = this.rand(-200, this.W + 200);",
    "    this.y       = this.rand(20, this.H * 0.45);",
    "    this.size    = this.rand(40, 90);",
    "    this.speed   = this.rand(0.15, 0.4);",
    "    this.opacity = this.rand(0.25, 0.55);",
    "    this.puffs   = [];",
    "    // สร้าง puffs (วงกลมซ้อน) สำหรับก้อนเมฆ",
    "    const n = Math.floor(this.rand(3, 6));",
    "    for (let i = 0; i < n; i++) {",
    "      this.puffs.push({",
    "        dx: this.rand(-this.size * 0.6, this.size * 0.6),",
    "        dy: this.rand(-this.size * 0.4, this.size * 0.2),",
    "        r:  this.rand(this.size * 0.5, this.size * 0.9),",
    "      });",
    "    }",
    "  }",
    "",
    "  update() {",
    "    this.x += this.speed;",
    "    if (this.x > this.W + 300) this.x = -300;",
    "  }",
    "",
    "  draw(ctx) {",
    "    ctx.save();",
    "    ctx.fillStyle = 'rgba(255,255,255,' + this.opacity + ')';",
    "    ctx.beginPath();",
    "    this.puffs.forEach(p => {",
    "      ctx.arc(this.x + p.dx, this.y + p.dy, p.r, 0, Math.PI * 2);",
    "    });",
    "    ctx.fill();",
    "    ctx.restore();",
    "  }",
    "}",
    "</code></pre>",
    "",
    "<h3>☀️ SunParticle — ดวงอาทิตย์หมุนพร้อม Lens Flare</h3>",
    "<pre><code>class SunParticle extends Particle {",
    "  init() {",
    "    this.x        = this.W * 0.78;",
    "    this.y        = this.H * 0.18;",
    "    this.size     = 65;",
    "    this.rotation = 0;",
    "    this.glow     = 0;",
    "    this.glowDir  = 1;",
    "  }",
    "",
    "  update() {",
    "    this.rotation += 0.004;",
    "    // pulse glow",
    "    this.glow += 0.01 * this.glowDir;",
    "    if (this.glow > 1 || this.glow < 0) this.glowDir *= -1;",
    "  }",
    "",
    "  draw(ctx) {",
    "    ctx.save();",
    "    ctx.translate(this.x, this.y);",
    "",
    "    // Outer glow (pulse)",
    "    const glowR = this.size * (1.8 + this.glow * 0.4);",
    "    const outer = ctx.createRadialGradient(0,0,0, 0,0,glowR);",
    "    outer.addColorStop(0,   'rgba(253,203,110,0.3)');",
    "    outer.addColorStop(1,   'rgba(253,203,110,0)');",
    "    ctx.fillStyle = outer;",
    "    ctx.beginPath();",
    "    ctx.arc(0, 0, glowR, 0, Math.PI * 2);",
    "    ctx.fill();",
    "",
    "    // Inner sun body",
    "    const inner = ctx.createRadialGradient(0,0,0, 0,0,this.size);",
    "    inner.addColorStop(0,   'rgba(253,230,138,1)');",
    "    inner.addColorStop(0.6, 'rgba(253,203,110,1)');",
    "    inner.addColorStop(1,   'rgba(245,158,11,1)');",
    "    ctx.fillStyle = inner;",
    "    ctx.beginPath();",
    "    ctx.arc(0, 0, this.size, 0, Math.PI * 2);",
    "    ctx.fill();",
    "",
    "    // รัศมีแสง 12 เส้น",
    "    ctx.rotate(this.rotation);",
    "    ctx.strokeStyle = 'rgba(253,203,110,0.4)';",
    "    ctx.lineWidth = 4;",
    "    ctx.lineCap = 'round';",
    "    for (let i = 0; i < 12; i++) {",
    "      ctx.rotate(Math.PI / 6);",
    "      ctx.beginPath();",
    "      ctx.moveTo(0, this.size * 0.7);",
    "      ctx.lineTo(0, this.size * 1.4);",
    "      ctx.stroke();",
    "    }",
    "    ctx.restore();",
    "  }",
    "}",
    "</code></pre>",
    "",
    "<h3>❄️ SnowParticle — เกล็ดหิมะหมุนลอย</h3>",
    "<pre><code>class SnowParticle extends Particle {",
    "  init() {",
    "    this.x       = this.rand(0, this.W);",
    "    this.y       = this.rand(-20, -5);",
    "    this.size    = this.rand(3, 9);",
    "    this.speed   = this.rand(0.5, 2.5);",
    "    this.drift   = this.rand(-0.5, 0.5);",
    "    this.wobble  = this.rand(0, Math.PI * 2);",
    "    this.wobbleSpeed = this.rand(0.02, 0.06);",
    "    this.opacity = this.rand(0.5, 1.0);",
    "    this.rotation = this.rand(0, Math.PI * 2);",
    "    this.rotSpeed = this.rand(-0.03, 0.03);",
    "  }",
    "",
    "  update() {",
    "    this.wobble += this.wobbleSpeed;",
    "    this.x += Math.sin(this.wobble) * 0.5 + this.drift;",
    "    this.y += this.speed;",
    "    this.rotation += this.rotSpeed;",
    "    if (this.y > this.H + 10) this.dead = true;",
    "  }",
    "",
    "  draw(ctx) {",
    "    ctx.save();",
    "    ctx.translate(this.x, this.y);",
    "    ctx.rotate(this.rotation);",
    "    ctx.fillStyle = 'rgba(255,255,255,' + this.opacity + ')';",
    "    // วาดรูป 6-point snowflake",
    "    for (let i = 0; i < 6; i++) {",
    "      ctx.rotate(Math.PI / 3);",
    "      ctx.fillRect(-1, 0, 2, this.size);",
    "    }",
    "    ctx.restore();",
    "  }",
    "}",
    "</code></pre>",
    "",
    "<h3>⚡ LightningParticle — ฟ้าแลบ</h3>",
    "<pre><code>class LightningParticle extends Particle {",
    "  init() {",
    "    this.x     = this.rand(this.W * 0.1, this.W * 0.9);",
    "    this.y     = 0;",
    "    this.life  = 0;",
    "    this.maxLife = this.rand(8, 20);  // frames",
    "    this.segments = this.generateBolt(this.x, 0, this.x + this.rand(-80,80), this.H * 0.7, 6);",
    "  }",
    "",
    "  generateBolt(x1, y1, x2, y2, depth) {",
    "    if (depth === 0) return [{ x: x1, y: y1 }, { x: x2, y: y2 }];",
    "    const mx = (x1 + x2) / 2 + this.rand(-30, 30);",
    "    const my = (y1 + y2) / 2;",
    "    return [",
    "      ...this.generateBolt(x1, y1, mx, my, depth - 1),",
    "      ...this.generateBolt(mx, my, x2, y2, depth - 1),",
    "    ];",
    "  }",
    "",
    "  update() {",
    "    this.life++;",
    "    if (this.life > this.maxLife) this.dead = true;",
    "  }",
    "",
    "  draw(ctx) {",
    "    const alpha = 1 - this.life / this.maxLife;",
    "    ctx.save();",
    "    ctx.strokeStyle = 'rgba(255,255,200,' + alpha + ')';",
    "    ctx.lineWidth = 2;",
    "    ctx.shadowColor = 'rgba(200,200,255,0.8)';",
    "    ctx.shadowBlur = 15;",
    "    ctx.beginPath();",
    "    this.segments.forEach((pt, i) => {",
    "      i === 0 ? ctx.moveTo(pt.x, pt.y) : ctx.lineTo(pt.x, pt.y);",
    "    });",
    "    ctx.stroke();",
    "    ctx.restore();",
    "  }",
    "}",
    "</code></pre>",
    "",
    "<h3>🎛️ Spawn Rate Table — จำนวนอนุภาคต่อ Frame</h3>",
    "<table>",
    "  <tr><th>Weather Type</th><th>Particle Class</th><th>Max Count</th><th>Spawn/Frame</th></tr>",
    "  <tr><td>sunny</td><td>SunParticle, StarParticle</td><td>1 sun + 50 stars</td><td>สร้างครั้งเดียว</td></tr>",
    "  <tr><td>cloudy</td><td>CloudParticle</td><td>8-12 clouds</td><td>ทุก 60 frames</td></tr>",
    "  <tr><td>rain (light)</td><td>RainParticle, CloudParticle</td><td>80 rain + 5 clouds</td><td>3/frame</td></tr>",
    "  <tr><td>rain (heavy)</td><td>RainParticle, CloudParticle</td><td>250 rain + 8 clouds</td><td>12/frame</td></tr>",
    "  <tr><td>storm</td><td>RainParticle, LightningParticle</td><td>300 rain + 3 lightning</td><td>15/frame + random</td></tr>",
    "  <tr><td>snow</td><td>SnowParticle</td><td>150 flakes</td><td>4/frame</td></tr>",
    "  <tr><td>fog</td><td>FogParticle</td><td>30 fog patches</td><td>2/frame</td></tr>",
    "</table>",
    "",
    "<pre><code>function spawnParticles(weatherType) {",
    "  switch (weatherType) {",
    "    case 'sunny':",
    "      if (!particles.find(p => p instanceof SunParticle))",
    "        particles.push(new SunParticle(canvas));",
    "      break;",
    "    case 'cloudy':",
    "      if (particles.filter(p => p instanceof CloudParticle).length < 10)",
    "        particles.push(new CloudParticle(canvas));",
    "      break;",
    "    case 'rain':",
    "      if (particles.filter(p => p instanceof RainParticle).length < 200) {",
    "        for (let i = 0; i < 6; i++)",
    "          particles.push(new RainParticle(canvas));",
    "      }",
    "      break;",
    "    case 'storm':",
    "      if (particles.filter(p => p instanceof RainParticle).length < 300)",
    "        for (let i = 0; i < 12; i++)",
    "          particles.push(new RainParticle(canvas));",
    "      if (Math.random() < 0.015)  // 1.5% chance per frame",
    "        particles.push(new LightningParticle(canvas));",
    "      break;",
    "    case 'snow':",
    "      if (particles.filter(p => p instanceof SnowParticle).length < 150)",
    "        for (let i = 0; i < 4; i++)",
    "          particles.push(new SnowParticle(canvas));",
    "      break;",
    "  }",
    "}</code></pre>",
    "",
    "<div class='tip-box'><strong>💡</strong> Pro Tip: ใช้ Object Pooling ดึง Particle กลับมาใช้ซ้ำแทนการ new ตลอดเวลา ลด Garbage Collection และทำให้ FPS สม่ำเสมอมากขึ้น!</div>",
]

# ── Chapter 5 ─────────────────────────────────────────────────────────────────

ch5 = [
    "<h2>📦 รวมโค้ดเต็ม — คัดลอกไปใช้ได้ทันที + Deploy!</h2>",
    "<p>โค้ดทั้งหมดอยู่ใน <strong>index.html ไฟล์เดียว</strong> แค่สร้างไฟล์ → วางโค้ด → เปิด Browser → เสร็จ! ในบทนี้เราจะดูโครงสร้างสมบูรณ์ การ Deploy ออนไลน์ และการแก้ Bug ที่พบบ่อย</p>",
    "",
    "<h3>📝 Complete HTML Structure</h3>",
    "<pre><code>&lt;!DOCTYPE html&gt;",
    "&lt;html lang='th'&gt;",
    "&lt;head&gt;",
    "  &lt;meta charset='UTF-8'&gt;",
    "  &lt;meta name='viewport' content='width=device-width, initial-scale=1.0'&gt;",
    "  &lt;meta name='description' content='เว็บพยากรณ์อากาศ 77 จังหวัดไทย พร้อมแอนิเมชัน Canvas'&gt;",
    "  &lt;title&gt;🌤️ พยากรณ์อากาศไทย&lt;/title&gt;",
    "  &lt;!-- Google Font --&gt;",
    "  &lt;link rel='preconnect' href='https://fonts.googleapis.com'&gt;",
    "  &lt;link href='https://fonts.googleapis.com/css2?family=Prompt:wght@400;600;800&amp;display=swap' rel='stylesheet'&gt;",
    "  &lt;style&gt;",
    "    /* ── Reset ── */",
    "    *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }",
    "    body {",
    "      font-family: 'Prompt', 'Noto Sans Thai', sans-serif;",
    "      overflow: hidden;",
    "      min-height: 100dvh;",
    "    }",
    "",
    "    /* ── Canvas Background ── */",
    "    #weatherCanvas {",
    "      position: fixed; inset: 0;",
    "      width: 100%; height: 100%;",
    "      z-index: 0;",
    "    }",
    "",
    "    /* ── App Container ── */",
    "    .app {",
    "      position: relative; z-index: 1;",
    "      min-height: 100dvh;",
    "      display: flex; flex-direction: column;",
    "      align-items: center; justify-content: center;",
    "      padding: 20px; gap: 20px;",
    "    }",
    "",
    "    /* ── Weather Card ── */",
    "    .card {",
    "      background: rgba(255,255,255,0.75);",
    "      backdrop-filter: blur(25px);",
    "      -webkit-backdrop-filter: blur(25px);",
    "      border: 1px solid rgba(255,255,255,0.3);",
    "      border-radius: 24px;",
    "      padding: 32px;",
    "      max-width: 420px; width: 100%;",
    "      text-align: center;",
    "      animation: fadeIn 0.5s ease;",
    "    }",
    "",
    "    /* ── Typography ── */",
    "    .temp  { font-size: 80px; font-weight: 800; line-height: 1; }",
    "    .emoji { font-size: 64px; display: block; margin-bottom: 12px; }",
    "    .desc  { font-size: 18px; color: #555; margin: 8px 0; }",
    "    .wind  { font-size: 14px; color: #888; }",
    "",
    "    /* ── Province Select ── */",
    "    .province-select {",
    "      width: 100%; padding: 12px 16px;",
    "      border: 1px solid rgba(0,0,0,0.15);",
    "      border-radius: 12px;",
    "      font-family: inherit; font-size: 16px;",
    "      background: rgba(255,255,255,0.8);",
    "      cursor: pointer; margin-top: 16px;",
    "    }",
    "",
    "    /* ── Forecast Strip ── */",
    "    .forecast {",
    "      display: flex; gap: 10px; overflow-x: auto;",
    "      scroll-snap-type: x mandatory;",
    "      -ms-overflow-style: none; scrollbar-width: none;",
    "      padding: 8px 0; max-width: 420px; width: 100%;",
    "    }",
    "    .forecast::-webkit-scrollbar { display: none; }",
    "    .forecast-day {",
    "      flex: 0 0 90px;",
    "      background: rgba(255,255,255,0.6);",
    "      backdrop-filter: blur(15px);",
    "      border: 1px solid rgba(255,255,255,0.3);",
    "      border-radius: 16px;",
    "      padding: 12px 8px; text-align: center;",
    "      scroll-snap-align: start;",
    "      font-size: 13px;",
    "    }",
    "",
    "    /* ── Animations ── */",
    "    @keyframes fadeIn {",
    "      from { opacity:0; transform: translateY(16px); }",
    "      to   { opacity:1; transform: translateY(0); }",
    "    }",
    "    @keyframes float {",
    "      0%,100% { transform: translateY(0); }",
    "      50%      { transform: translateY(-8px); }",
    "    }",
    "    .emoji { animation: float 3s ease-in-out infinite; }",
    "  &lt;/style&gt;",
    "&lt;/head&gt;",
    "&lt;body&gt;",
    "  &lt;canvas id='weatherCanvas' aria-hidden='true'&gt;&lt;/canvas&gt;",
    "  &lt;main class='app'&gt;",
    "    &lt;div class='card' id='mainCard'&gt;",
    "      &lt;span class='emoji' id='wEmoji'&gt;⏳&lt;/span&gt;",
    "      &lt;div class='temp'  id='wTemp'&gt;--°&lt;/div&gt;",
    "      &lt;div class='desc'  id='wDesc'&gt;กำลังโหลด...&lt;/div&gt;",
    "      &lt;div class='wind'  id='wWind'&gt;&lt;/div&gt;",
    "      &lt;select class='province-select' id='provinceSelect'&gt;&lt;/select&gt;",
    "      &lt;button id='geoBtn' style='margin-top:10px;padding:8px 16px;border-radius:8px;border:none;background:#74b9ff;color:#fff;cursor:pointer;font-family:inherit;'&gt;📍 ตำแหน่งของฉัน&lt;/button&gt;",
    "    &lt;/div&gt;",
    "    &lt;div class='forecast' id='forecastStrip'&gt;&lt;/div&gt;",
    "  &lt;/main&gt;",
    "  &lt;script&gt;",
    "    // ── JavaScript ทั้งหมดอยู่ตรงนี้ ──",
    "    // (ดูโค้ดจากบทที่ 1-4 แล้วรวมกัน)",
    "  &lt;/script&gt;",
    "&lt;/body&gt;",
    "&lt;/html&gt;</code></pre>",
    "",
    "<h3>💾 localStorage Settings Persistence</h3>",
    "<pre><code>const SETTINGS_KEY = 'weather_settings';",
    "",
    "function saveSettings(settings) {",
    "  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));",
    "}",
    "",
    "function loadSettings() {",
    "  try {",
    "    return JSON.parse(localStorage.getItem(SETTINGS_KEY)) || {};",
    "  } catch { return {}; }",
    "}",
    "",
    "// บันทึกจังหวัดที่เลือกล่าสุด",
    "select.addEventListener('change', () => {",
    "  saveSettings({ lastProvince: select.value });",
    "  loadWeather(select.value);",
    "});",
    "",
    "// โหลดจังหวัดล่าสุดตอนเปิด",
    "const { lastProvince } = loadSettings();",
    "if (lastProvince) select.value = lastProvince;</code></pre>",
    "",
    "<h3>🐛 Common Bugs — ปัญหาที่พบบ่อยและวิธีแก้</h3>",
    "<table>",
    "  <tr><th>ปัญหา</th><th>สาเหตุ</th><th>วิธีแก้</th></tr>",
    "  <tr><td>Canvas เบลอบน Retina</td><td>ไม่ได้ scale ตาม devicePixelRatio</td><td>ใช้ setupHiDPICanvas() ตามบทที่ 3</td></tr>",
    "  <tr><td>Glassmorphism ไม่ work บน Safari</td><td>ต้องใส่ -webkit- prefix</td><td>ใส่ทั้ง backdrop-filter และ -webkit-backdrop-filter</td></tr>",
    "  <tr><td>API Error CORS</td><td>เรียก API จาก file:// protocol</td><td>รันผ่าน Live Server หรือ http-server</td></tr>",
    "  <tr><td>Geolocation ไม่ทำงาน</td><td>ต้องใช้ HTTPS</td><td>Deploy ขึ้น Vercel/GitHub Pages ก่อน</td></tr>",
    "  <tr><td>FPS ต่ำบนมือถือ</td><td>อนุภาคเยินเกิน</td><td>ลด MAX_PARTICLES บน mobile ด้วย isMobile check</td></tr>",
    "  <tr><td>ข้อมูลไม่ update</td><td>ติด cache เก่า</td><td>กด Ctrl+Shift+R หรือล้าง localStorage</td></tr>",
    "  <tr><td>Canvas ไม่ resize</td><td>ลืม addEventListener('resize')</td><td>ใส่ window.addEventListener('resize', resizeCanvas)</td></tr>",
    "</table>",
    "",
    "<h3>🌐 GitHub Pages Deployment</h3>",
    "<pre><code># ขั้นตอน Deploy บน GitHub Pages",
    "",
    "# 1. สร้าง Repository ใน GitHub",
    "#    ชื่อ: weather-app (หรืออะไรก็ได้)",
    "",
    "# 2. Push โค้ดขึ้น GitHub",
    "git init",
    "git add index.html",
    "git commit -m 'Initial commit'",
    "git branch -M main",
    "git remote add origin https://github.com/USERNAME/weather-app.git",
    "git push -u origin main",
    "",
    "# 3. เปิด GitHub Pages",
    "#    ไป Settings → Pages",
    "#    Source: Deploy from branch",
    "#    Branch: main / (root)",
    "#    กด Save",
    "",
    "# 4. ได้ URL: https://USERNAME.github.io/weather-app/",
    "#    (รอประมาณ 1-2 นาทีก่อน URL จะใช้งานได้)</code></pre>",
    "",
    "<h3>🚀 Vercel Deployment (แนะนำ — ง่ายที่สุด)</h3>",
    "<pre><code># วิธีที่ 1: Drag &amp; Drop (ง่ายสุด!)",
    "# 1. ไปที่ vercel.com → Log in ด้วย GitHub",
    "# 2. กด New Project → Import Git Repository",
    "# 3. หรือ drag ลาก folder ไปวางที่หน้า vercel.com",
    "# 4. ได้ URL: https://weather-app-xxx.vercel.app",
    "",
    "# วิธีที่ 2: Vercel CLI",
    "npm install -g vercel",
    "vercel login",
    "vercel --prod",
    "# ได้ URL ทันที!</code></pre>",
    "",
    "<h3>✅ Performance Checklist ก่อน Deploy</h3>",
    "<ul>",
    "  <li>☐ ทดสอบ FPS บน mobile จริง (ไม่ใช่แค่ DevTools)</li>",
    "  <li>☐ ลด MAX_PARTICLES บน mobile (&lt; 768px)</li>",
    "  <li>☐ ตรวจ Console ว่าไม่มี Error หรือ Warning</li>",
    "  <li>☐ ทดสอบ offline — ข้อมูล cache ยังโชว์อยู่ไหม?</li>",
    "  <li>☐ ทดสอบ Geolocation บน HTTPS</li>",
    "  <li>☐ ตรวจ Accessibility — ใช้ Tab navigate ได้ไหม?</li>",
    "  <li>☐ เพิ่ม meta description สำหรับ SEO</li>",
    "  <li>☐ ใส่ favicon.ico</li>",
    "  <li>☐ ทดสอบบน Chrome, Firefox, Safari</li>",
    "  <li>☐ Lighthouse Score ควรได้ 90+</li>",
    "</ul>",
    "",
    "<h3>💡 Enhancement Ideas — ต่อยอดโปรเจค</h3>",
    "<ul>",
    "  <li>🔔 <strong>Push Notification</strong> แจ้งเตือนเมื่อฝนจะตก (Web Push API)</li>",
    "  <li>📊 <strong>Chart อุณหภูมิ</strong> รายชั่วโมงด้วย Canvas หรือ Chart.js</li>",
    "  <li>🗺️ <strong>แผนที่ Weather</strong> overlay บน Google Maps</li>",
    "  <li>🌍 <strong>เพิ่ม Location Search</strong> ค้นหาเมืองทั่วโลก</li>",
    "  <li>📱 <strong>PWA</strong> ทำให้ install บนมือถือได้เหมือน App จริง</li>",
    "  <li>🎙️ <strong>Voice Command</strong> พูดชื่อจังหวัดได้ (Web Speech API)</li>",
    "  <li>🌡️ <strong>UV Index + AQI</strong> เพิ่มข้อมูลสุขภาพ</li>",
    "  <li>🌊 <strong>Tide Information</strong> สำหรับจังหวัดชายทะเล</li>",
    "</ul>",
    "",
    "<div class='tip-box'><strong>💡</strong> สรุป: คอร์สนี้สอนให้เข้าใจ Fetch API + async/await, CSS Glassmorphism Design System, HTML5 Canvas 2D API, OOP Particle System ใน JavaScript, localStorage, Geolocation และ Deploy ฟรีด้วย GitHub Pages + Vercel — ทักษะที่นักพัฒนาทุกคนควรมี!</div>",
]

# ── Assemble ──────────────────────────────────────────────────────────────────

chapters_data = [
    (0, 'intro-weather-app',  '🌩️', 'ภาพรวมโปรเจค Weather App',          ch0),
    (1, 'data-fetching',      '📡', 'Data Fetching — ดึงข้อมูลจริง',       ch1),
    (2, 'glassmorphism-ui',   '🎨', 'Glassmorphism UI — สวยด้วย CSS ล้วน', ch2),
    (3, 'canvas-animation',   '✨', 'HTML5 Canvas — แอนิเมชัน 60FPS',       ch3),
    (4, 'particle-system',    '🎆', 'Particle System — ฝน เมฆ แดด',         ch4),
    (5, 'full-code',          '📦', 'รวมโค้ดเต็ม — คัดลอกได้เลย!',         ch5),
]

lines = ['export const chapters = [']
for i, (num, slug, emoji, title, content) in enumerate(chapters_data):
    line = chapter(num, slug, emoji, title, content)
    if i < len(chapters_data) - 1:
        line += ','
    lines.append(line)
lines.append('];')
lines.append('')

output = '\n'.join(lines)

# Write output
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(output)

size = os.path.getsize(OUT)
print(f'✅ Written: {OUT}')
print(f'📦 Size: {size:,} bytes ({size/1024:.1f} KB)')
print(f'📝 Lines: {output.count(chr(10))+1}')
